/*
 * generated by Xtext 2.26.0
 */
package org.eclipse.efbt.openregspecs.ui;

import com.google.inject.Injector;
import org.eclipse.efbt.openregspecs.OpenRegSpecsDSL.ui.internal.OpenRegSpecsDSLActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OpenRegSpecsDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(OpenRegSpecsDSLActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		OpenRegSpecsDSLActivator activator = OpenRegSpecsDSLActivator.getInstance();
		return activator != null ? activator.getInjector(OpenRegSpecsDSLActivator.ORG_ECLIPSE_EFBT_OPENREGSPECS_OPENREGSPECSDSL) : null;
	}

}
