<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test_definition" nsURI="http://www.eclipse.org/test_definition"
    nsPrefix="test_definition">
  <eClassifiers xsi:type="ecore:EClass" name="TestContraints">
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" eType="#//TestTemplate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="givenParams" upperBound="-1"
        eType="#//Param" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whenParams" upperBound="-1"
        eType="#//Param" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenParams" upperBound="-1"
        eType="#//Param" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestTemplateModule" eSuperTypes="../../org.eclipse.efbt.cocamo.core.model.module_management/model/module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="templates" upperBound="-1"
        eType="#//TestTemplate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestTemplate">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="givenText" eType="#//ClauseText"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whenText" eType="#//ClauseText"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenText" eType="#//ClauseText"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="givenParams" upperBound="-1"
        eType="#//Param" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whenParams" upperBound="-1"
        eType="#//Param" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenParams" upperBound="-1"
        eType="#//Param" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestConstraintsModule" eSuperTypes="../../org.eclipse.efbt.cocamo.core.model.module_management/model/module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverageTestSets" upperBound="-1"
        eType="#//TestContraints" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testContraints" eType="#//TestContraints"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="given" eType="#//Given"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="when" eType="#//When" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#//Then" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="E2ETestDefinition" eSuperTypes="#//TestDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnitTestDefinition" eSuperTypes="#//TestDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Clause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//ClauseText"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//Param" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regulatoryTextLinks" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.efbt.requirements.core.model.requirements_text/model/requirements_text.ecore#//TitledRequirementsSection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Param">
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Given" eSuperTypes="#//Clause"/>
  <eClassifiers xsi:type="ecore:EClass" name="When" eSuperTypes="#//Clause"/>
  <eClassifiers xsi:type="ecore:EClass" name="Then" eSuperTypes="#//Clause"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClauseText">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoverageGrid">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverageTestSet" eType="#//TestContraints"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverageGridPoints" eType="#//CoverageGridPoint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoverageGridPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestDefinitionModule" eSuperTypes="../../org.eclipse.efbt.cocamo.core.model.module_management/model/module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testDefinitions" upperBound="-1"
        eType="#//TestDefinition" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
