<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cell_transformation_logic" nsURI="http://www.eclipse.org/cell_transformation_logic"
    nsPrefix="cell_transformation_logic">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value=" This package describes the SpreadsheetLineageModel, SpreadsheetLineageModels store the actaul lineage between calculated results, and input data, with lineage recorded between all the intermediate datasets which may have been calculated to get to the final results.&#xA;"/>
  </eAnnotations>
  <eAnnotations source="license">
    <details key="license" value="Copyright (c) 2020 Bird Software Solutions Ltd&#xA; All rights reserved. This file and the accompanying materials are made available under the terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at http://www.eclipse.org/legal/epl-v20.html&#xA;&#xA;SPDX-License-Identifier: EPL-2.0 &#xA;&#xA; Contributors:&#xA; Neil Mackenzie - initial API and implementation&#xD;"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="FormulaCell" eSuperTypes="../../org.eclipse.efbt.aorta.model.column_structured_data/model/column_structured_data.ecore#//Cell">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value=" A derived Cell, which contains a function of other cells (much like an Excel cell may have a formula of other cells)"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="FormulaCell"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="ecore:EClass ../../org.eclipse.efbt.aorta.model.functions/model/aortafunctions.ecore#//Function"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The  Function which derived the cell value."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="function"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Cell Value"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="value"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DerivedColumnStructuredData" eSuperTypes="../../org.eclipse.efbt.aorta.model.column_structured_data/model/column_structured_data.ecore#//ColumnStructuredData">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value=" data for derived cubes "/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DerivedColumnStructuredData"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//DerivedRowData"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The  Rows of data"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="rows"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cube" eType="ecore:EClass ../../org.eclipse.efbt.aorta.model.column_structures/model/column_structures.ecore#//ColumnStructuredEntity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The associated cube"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="cube"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceColumnStructuredData"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.efbt.aorta.model.column_structured_data/model/column_structured_data.ecore#//ColumnStructuredData">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The cube data"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="sourceColumnStructuredData"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DerivedRowData" eSuperTypes="../../org.eclipse.efbt.aorta.model.column_structured_data/model/column_structured_data.ecore#//RowData">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value=" A row of derived data "/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="DerivedRowData"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formulaCells" upperBound="-1"
        eType="#//FormulaCell" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The derived cells"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="formulaCells"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialDerivedCells" eType="#//FormulaCell"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The special DerivedCells, not created by functions which use cells from source rows."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="specialDerivedCells"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceRows" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.efbt.aorta.model.column_structured_data/model/column_structured_data.ecore#//RowData">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="sourceRows"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="source rows of the derived row"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionTag" eSuperTypes="../../org.eclipse.efbt.aorta.model.requirements_text/model/requirements_text.ecore#//Tag">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="ecore:EClass ../../org.eclipse.efbt.aorta.model.functions/model/aortafunctions.ecore#//Function"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormulaCellTag" eSuperTypes="../../org.eclipse.efbt.aorta.model.requirements_text/model/requirements_text.ecore#//Tag">
    <eStructuralFeatures xsi:type="ecore:EReference" name="formulaCell" eType="#//FormulaCell"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnStructuredDataTag" eSuperTypes="../../org.eclipse.efbt.aorta.model.requirements_text/model/requirements_text.ecore#//Tag">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnStructuredData" eType="ecore:EClass ../../org.eclipse.efbt.aorta.model.column_structured_data/model/column_structured_data.ecore#//ColumnStructuredData"/>
  </eClassifiers>
</ecore:EPackage>
