cd regdna/eclipse_model
mvn install
cd ../..
cd regdna/dsl/org.eclipse.efbt.regdna.dsl.parent
mvn install
cd ../../..
cd regpot_desktop/components
mvn install
cd ../..  
cd regpot_desktop/installation
mvn install
cd ../..