cd cocalimo\core\model
mvn install
cd ..\..\..
cd cocalimo\core\ui_sirius
mvn install
cd ..\..\..
cd cocalimo\smcubes\model
mvn install
cd ..\..\..
 cd cocalimo\smcubes\modelquery
mvn install
cd ..\..\..
 cd cocalimo\smcubes\ui_sirius
mvn install
cd ..\..\..
cd cocalimo\smcubes_with_lineage\model
mvn install
cd ..\..\..
cd cocalimo\smcubes_with_lineage\modelquery
mvn install
cd ..\..\..
cd cocalimo\smcubes_with_lineage\ui_sirius
mvn install
cd ..\..\..
cd cocalimo\trl\model
mvn install
cd ..\..\..
cd cocalimo\trl\modelquery
mvn install
cd ..\..\..
cd cocalimo\trl\ui_sirius
mvn install
cd ..\..\..
cd cocason\org.eclipse.efbt.cocason.dsl.cocason.parent
mvn install 
cd ..\..                   
cd controller\ldm
mvn install
cd ..\..
cd controller\smcubes\access_dependencies
mvn install
cd ..\..\..
cd controller\smcubes\component
mvn install
cd ..\..\..
cd controller\trl\component
mvn install
cd ..\..\..
cd controller\trl\ui_sirius
mvn install
cd ..\..\..
cd installations\complete_repo\
mvn install
cd ..\..