
pwd
cd cocalimo/core/model
mvn install
cd ../../..
cd cocalimo/core/ui_sirius
mvn install
cd ../../..
cd cocalimo/smcubes/model
mvn install
cd ../../..
 cd cocalimo/smcubes/modelquery
mvn install
cd ../../..
 cd cocalimo/smcubes/ui_sirius
mvn install
cd ../../..
cd cocalimo/smcubes_with_lineage/model
mvn install
cd ../../..
cd cocalimo/smcubes_with_lineage/modelquery
mvn install
cd ../../..
cd cocalimo/smcubes_with_lineage/ui_sirius
mvn install
cd ../../..
cd cocalimo/dtm/model
mvn install
cd ../../..
cd cocalimo/dtm/modelquery
mvn install
cd ../../..
cd cocalimo/dtm/ui_sirius
mvn install
cd ../..                   
cd controller/ldm
mvn install
cd ../..
cd controller/smcubes/access_dependencies_external
mvn install
cd ../../..
cd controller/smcubes/access_dependencies_plugin
mvn install
cd ../../..
cd controller/smcubes/component
mvn install
cd ../../..
cd controller/dtm/component
mvn install
cd ../../..
cd controller/dtm/ui_sirius
mvn install
cd ../../..
cd installations/complete_repo/
mvn install
cd ../..
