<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="datapoints" nsURI="http://www.eclipse.org/datapoints" nsPrefix="datapoints">
  <eClassifiers xsi:type="ecore:EClass" name="DataPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="combinationItems" upperBound="-1"
        eType="#//DatapointCombinationItem"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="measureColumn" eType="ecore:EClass ../../org.eclipse.efbt.aorta.model.column_structures/model/column_structures.ecore#//Column"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatapointCombinationItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" eType="ecore:EClass ../../org.eclipse.efbt.aorta.model.column_structures/model/column_structures.ecore#//Column"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" eType="ecore:EClass ../../org.eclipse.efbt.aorta.model.column_structures/model/column_structures.ecore#//EnumMember"/>
  </eClassifiers>
</ecore:EPackage>
