<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="domain_model_mapping" nsURI="http://www.eclipse.org/domain_model_mapping"
    nsPrefix="domain_model_mapping">
  <eClassifiers xsi:type="ecore:EClass" name="LeafModuleToVersionedSQLViewsModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheme" eType="ecore:EClass ../../org.eclipse.efbt.cocamo.core.model.functionality_module/model/functionality_module.ecore#//LeafFunctionalityModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="ecore:EClass trl_sql_views.ecore#//VersionedSQLViewsModule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LeafModuleToVersionedCubeSchemaModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheme" eType="ecore:EClass ../../org.eclipse.efbt.cocamo.core.model.functionality_module/model/functionality_module.ecore#//LeafFunctionalityModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="ecore:EClass transformation.ecore#//VersionedCubeSchemaModule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LeafModuleToReportCellViewModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheme" eType="ecore:EClass ../../org.eclipse.efbt.cocamo.core.model.functionality_module/model/functionality_module.ecore#//LeafFunctionalityModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="ecore:EClass trl_report_cell_views.ecore#//ReportCellViewModule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScenarioToCodeConditions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenario" eType="ecore:EClass ../../org.eclipse.efbt.cocamo.core.model.functionality_module/model/scenarios.ecore#//Scenario"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="codeConditions" upperBound="-1"
        eType="#//CodeCondition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeCondition"/>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnSettingCondition" eSuperTypes="#//CodeCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cube" eType="ecore:EClass ../../org.eclipse.efbt.cocamo.lineage.model.lineagecubes/model/cubes.ecore#//FreeBirdToolsCube"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="ecore:EClass ../../org.eclipse.efbt.cocamo.smcubes.model.core/model/core.ecore#//VARIABLE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterConditions" eType="ecore:EClass ../../org.eclipse.efbt.cocamo.core.model.functions/model/functions.ecore#//BasicFunction"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSetFilterCondition" eSuperTypes="#//CodeCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterConditions" eType="ecore:EClass ../../org.eclipse.efbt.cocamo.core.model.functions/model/functions.ecore#//BooleanFunction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cube" eType="ecore:EClass ../../org.eclipse.efbt.cocamo.lineage.model.lineagecubes/model/cubes.ecore#//FreeBirdToolsCube"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnionChoiceCondition" eSuperTypes="#//CodeCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cube" eType="ecore:EClass ../../org.eclipse.efbt.cocamo.lineage.model.lineagecubes/model/cubes.ecore#//FreeBirdToolsCube"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chosenCubes" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.efbt.cocamo.lineage.model.lineagecubes/model/cubes.ecore#//FreeBirdToolsCube"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainMappingModule" eSuperTypes="../../org.eclipse.efbt.cocamo.core.model.module_management/model/module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leafModuleToVersionedSQLViewsModules"
        upperBound="-1" eType="#//LeafModuleToVersionedSQLViewsModule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leafModuleToVersionedCubeSchemaModules"
        upperBound="-1" eType="#//LeafModuleToVersionedCubeSchemaModule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leafModuleToReportCellViewModules"
        upperBound="-1" eType="#//LeafModuleToReportCellViewModule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioToCodeConditions"
        upperBound="-1" eType="#//ScenarioToCodeConditions" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
