<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bdd_test_definitions" nsURI="http://www.eclipse.org/bdd_test_definitions"
    nsPrefix="bdd_test_definitions">
  <eClassifiers xsi:type="ecore:EClass" name="BDDTestDefinition" eSuperTypes="test_definition.ecore#//E2ETestDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="BDDTestDefinitionModule" eSuperTypes="module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testDefinitions" upperBound="-1"
        eType="#//BDDTestDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericBDD" eSuperTypes="#//BDDTestDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="given" eType="#//GenericGiven"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="when" eType="#//GenericWhen"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#//GenericThen"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericGiven" eSuperTypes="#//BDDClause"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenericWhen" eSuperTypes="#//BDDClause"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenericThen" eSuperTypes="#//BDDClause"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClauseText">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BDDClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="regulatoryTextLinks" upperBound="-1"
        eType="ecore:EClass requirements_text.ecore#//TitledRequirementsSection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//ClauseText"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//BDDParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BDDParam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
</ecore:EPackage>
