<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test_definition" nsURI="http://www.eclipse.org/test_definition"
    nsPrefix="test_definition">
  <eClassifiers xsi:type="ecore:EClass" name="TestDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="E2ETestDefinition" eSuperTypes="#//TestDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnitTestDefinition" eSuperTypes="#//TestDefinition"/>
</ecore:EPackage>
