<?xml version='1.0' encoding='UTF-8'?>
<data_meta_model:EntityModule xmlns:xmi="http://www.omg.org/XMI" xmlns:data_meta_model="http://www.eclipse.org/efbt/data_meta_model" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="bird" nsPrefix="bird" nsURI="&quot;http://www.eclipse.org/bird&quot;" xmi:version="2.0">
  <entities xsi:type="data_meta_model:BasicEntity" name="Commodity_risk_factor" superClass="//@entities.14"/>
  <entities xsi:type="data_meta_model:BasicEntity" name="CSR_non_securitisation_risk_factor" superClass="//@entities.14">
    <attributes xsi:type="data_meta_model:OneToOneRelationshipAttribute" entity="//@entities.12" name="theOrganisation" mandatory="true"/>
  </entities>
  <entities xsi:type="data_meta_model:BasicEntity" name="Curvature" superClass="//@entities.15"/>
  <entities xsi:type="data_meta_model:BasicEntity" name="Delta_sensitivities_correlated_and_aggregated_derived">
    <attributes xsi:type="data_meta_model:OneToManyRelationshipAttribute" entity="//@entities.5" name="theDelta_sensitivity_combinations_deriveds" mandatory="true"/>
  </entities>
  <entities xsi:type="data_meta_model:BasicEntity" name="Delta_sensitivity" superClass="//@entities.15"/>
  <entities xsi:type="data_meta_model:BasicEntity" name="Delta_sensitivity_combinations_derived">
    <attributes xsi:type="data_meta_model:OneToOneRelationshipAttribute" entity="//@entities.11" name="theNetted_delta_sensitivities_per_risk_factor_and_tenor_derived" mandatory="true"/>
    <attributes xsi:type="data_meta_model:OneToOneRelationshipAttribute" entity="//@entities.11" name="theNetted_delta_sensitivities_per_risk_factor_and_tenor_derived1" mandatory="true"/>
  </entities>
  <entities xsi:type="data_meta_model:BasicEntity" name="Equity_issue" superClass="//@entities.19"/>
  <entities xsi:type="data_meta_model:BasicEntity" name="Equity_risk_factor" superClass="//@entities.14">
    <attributes xsi:type="data_meta_model:OneToOneRelationshipAttribute" entity="//@entities.6" name="theEquity_issue" mandatory="true"/>
  </entities>
  <entities xsi:type="data_meta_model:BasicEntity" name="FX_risk_factor" superClass="//@entities.14"/>
  <entities xsi:type="data_meta_model:BasicEntity" name="GIRR_risk_factor" superClass="//@entities.14"/>
  <entities xsi:type="data_meta_model:BasicEntity" name="KB_per_bucket_derived">
    <attributes xsi:type="data_meta_model:OneToOneRelationshipAttribute" entity="//@entities.3" name="theDelta_sensitivities_correlated_and_aggregated_derived" mandatory="true"/>
    <attributes xsi:type="data_meta_model:OneToOneRelationshipAttribute" entity="//@entities.22" name="theTotal_delta_sensitivity_per_bucket_derived" mandatory="true"/>
  </entities>
  <entities xsi:type="data_meta_model:BasicEntity" name="Netted_delta_sensitivities_per_risk_factor_and_tenor_derived">
    <attributes xsi:type="data_meta_model:OneToManyRelationshipAttribute" entity="//@entities.4" name="theDelta_sensitivitys" mandatory="true"/>
    <attributes xsi:type="data_meta_model:OneToOneRelationshipAttribute" entity="//@entities.14" name="theRisk_factor" mandatory="true"/>
  </entities>
  <entities xsi:type="data_meta_model:BasicEntity" name="Organisation"/>
  <entities xsi:type="data_meta_model:BasicEntity" name="OUTPUT_LAYER_FRTB"/>
  <entities xsi:type="data_meta_model:BasicEntity" name="Risk_factor"/>
  <entities xsi:type="data_meta_model:BasicEntity" name="Risk_measure">
    <attributes xsi:type="data_meta_model:OneToOneRelationshipAttribute" entity="//@entities.14" name="theRisk_factor" mandatory="true"/>
    <attributes xsi:type="data_meta_model:OneToOneRelationshipAttribute" entity="//@entities.20" name="theSecurity_or_exchange_tradable_derivative_position" mandatory="true"/>
  </entities>
  <entities xsi:type="data_meta_model:BasicEntity" name="Securitisation" superClass="//@entities.19"/>
  <entities xsi:type="data_meta_model:BasicEntity" name="Securitisation_CTP_risk_factor_" superClass="//@entities.14"/>
  <entities xsi:type="data_meta_model:BasicEntity" name="Securitisation_non_CTP_risk_factor" superClass="//@entities.14">
    <attributes xsi:type="data_meta_model:OneToOneRelationshipAttribute" entity="//@entities.16" name="theSecuritisation" mandatory="true"/>
  </entities>
  <entities xsi:type="data_meta_model:BasicEntity" name="Security_issue">
    <attributes xsi:type="data_meta_model:OneToOneRelationshipAttribute" entity="//@entities.12" name="theOrganisation" mandatory="true"/>
  </entities>
  <entities xsi:type="data_meta_model:BasicEntity" name="Security_or_exchange_tradable_derivative_position"/>
  <entities xsi:type="data_meta_model:BasicEntity" name="Summed_delta_sensitivities_per_position_and_risk_factor_derived">
    <attributes xsi:type="data_meta_model:OneToManyRelationshipAttribute" entity="//@entities.4" name="theDelta_sensitivitys" mandatory="true"/>
    <attributes xsi:type="data_meta_model:OneToOneRelationshipAttribute" entity="//@entities.20" name="theSecurity_or_exchange_tradable_derivative_position" mandatory="true"/>
    <attributes xsi:type="data_meta_model:OneToOneRelationshipAttribute" entity="//@entities.14" name="theRisk_factor" mandatory="true"/>
  </entities>
  <entities xsi:type="data_meta_model:BasicEntity" name="Total_delta_sensitivity_per_bucket_derived">
    <attributes xsi:type="data_meta_model:OneToManyRelationshipAttribute" entity="//@entities.11" name="theNetted_delta_sensitivities_per_risk_factor_and_tenor_deriveds" mandatory="true"/>
  </entities>
  <entities xsi:type="data_meta_model:BasicEntity" name="Vega_sensitivity" superClass="//@entities.15"/>
</data_meta_model:EntityModule>
