<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="efbt_advanced_data_definition" nsURI="http://www.eclipse.org/efbt/efbt_advanced_data_definition"
    nsPrefix="efbt_advanced_data_definition">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value=" This package describes advanced Varaible which are in the form of Structs or Arrays.&#xA; &#xD;&#xA;"/>
  </eAnnotations>
  <eAnnotations source="license">
    <details key="license" value="Copyright (c) 2020 Bird Software Solutions Ltd&#xA; All rights reserved. This file and the accompanying materials are made available under the terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at http://www.eclipse.org/legal/epl-v20.html&#xA;&#xA;SPDX-License-Identifier: EPL-2.0 &#xA;&#xA; Contributors:&#xA; Neil Mackenzie - initial API and implementation&#xD;"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="AdvancedTypedVariable" eSuperTypes="../../org.eclipse.efbt.cocalimo.smcubes.model.core/model/core.ecore#//VARIABLE">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An advanced Variable which is in the form of a Struct or Array."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayTypedVariable" eSuperTypes="#//AdvancedTypedVariable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Variable which is an Array of Structs, where the structs have type defined by the cubeType."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cubeType" eType="ecore:EClass cubes.ecore#//BaseCube">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A cube which describes the type of structs held in the array"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayTypedVariableModule" eSuperTypes="../../org.eclipse.efbt.cocalimo.core.model.module_management/model/module_management.ecore#//Module">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Module containing a set of ArrayTypeVariables"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrayTypedVariables" upperBound="-1"
        eType="#//ArrayTypedVariable" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The set of ArrayTypeVariables"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructTypedVariable" eSuperTypes="#//AdvancedTypedVariable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An Variable which is efined as group of variables. We dpo not specify the group of variables, but rather we sate that they should be the same as the variables associated with a BaseCube.  Not that it is CubeSchemas which allow us to determine which Varaibles are linked to a BaseCube . "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cubeType" eType="ecore:EClass cubes.ecore#//BaseCube">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The BaseCube associated with the StructVariable"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructTypedVariablesModule" eSuperTypes="../../org.eclipse.efbt.cocalimo.core.model.module_management/model/module_management.ecore#//Module">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Module containing a set of StructTypeVariables"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structTypeVariables" upperBound="-1"
        eType="#//StructTypedVariable" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The set of StructTypeVariables"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
