<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pack" nsURI="pack2" nsPrefix="pack">
  <eClassifiers xsi:type="ecore:EClass" name="Commodity_risk_factor" eSuperTypes="#//Risk_factor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Commodity_type" unique="false"
        eType="#//Commodity_type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Delivery_location" unique="false"
        eType="#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CSR_non_securitisation_risk_factor"
      eSuperTypes="#//Risk_factor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CSR_credit_quality" unique="false"
        eType="#//Rating_grade"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CSR_curve_type" unique="false"
        eType="#//CSR_curve_type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theOrganisation" lowerBound="1"
        eType="#//Organisation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Delta_sensitivities_correlated_and_aggregated_derived">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GIRR_delta_correlated_value_per_bucket"
        unique="false" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Sensitivities_correlated_and_aggregated_bucket_identifier"
        unique="false" eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theDelta_sensitivity_combinations_deriveds"
        upperBound="-1" eType="#//Delta_sensitivity_combinations_derived"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Delta_sensitivity_combinations_derived">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Delta_sensitivity_combination_identifier"
        unique="false" eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GIRR_delta_correlated_value"
        unique="false" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GIRR_delta_correlation_factor"
        unique="false" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theNetted_delta_sensitivities_per_risk_factor_and_tenor_derived"
        lowerBound="1" eType="#//Netted_delta_sensitivities_per_risk_factor_and_tenor_derived"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theNetted_delta_sensitivities_per_risk_factor_and_tenor_derived1"
        lowerBound="1" eType="#//Netted_delta_sensitivities_per_risk_factor_and_tenor_derived"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Equity_issue" eSuperTypes="#//Security_issue"/>
  <eClassifiers xsi:type="ecore:EClass" name="Equity_risk_factor" eSuperTypes="#//Risk_factor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Equity_factor_type" unique="false"
        eType="#//Equity_factor_type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theEquity_issue" lowerBound="1"
        eType="#//Equity_issue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FX_risk_factor" eSuperTypes="#//Risk_factor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ccy1" unique="false" eType="#//Currency"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ccy2" unique="false" eType="#//Currency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GIRR_risk_factor" eSuperTypes="#//Risk_factor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GIRR_risk_factor_type"
        unique="false" eType="#//GIRR_risk_factor_type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Main_currency" unique="false"
        eType="#//Currency"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Second_currency" unique="false"
        eType="#//Currency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KB_per_bucket_derived">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Bucket_identifier" unique="false"
        eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GIRR_delta_KB" unique="false"
        eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theDelta_sensitivities_correlated_and_aggregated_derived"
        lowerBound="1" eType="#//Delta_sensitivities_correlated_and_aggregated_derived"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theTotal_delta_sensitivity_per_bucket_derived"
        lowerBound="1" eType="#//Total_delta_sensitivity_per_bucket_derived"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Netted_delta_sensitivities_per_risk_factor_and_tenor_derived">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Bucket_identifier" unique="false"
        eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GIRR_delta_risk_weight"
        unique="false" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Netted_delta_sensitivities"
        unique="false" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Netted_delta_sensitivities_identifier"
        unique="false" eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Tenor" unique="false" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Weighted_GIRR_delta_sensitivity"
        unique="false" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Weighted_GIRR_delta_sensitivity_squared"
        unique="false" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theDelta_sensitivitys"
        upperBound="-1" eType="#//Risk_measure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theRisk_factor" lowerBound="1"
        eType="#//Risk_factor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Organisation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Economy" unique="false"
        eType="#//Economy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Market_cap" unique="false"
        eType="#//Market_cap"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Organisation_identifier"
        unique="false" eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Ratings_grade" unique="false"
        eType="#//Rating_grade"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Sector" unique="false"
        eType="#//Sector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OUTPUT_LAYER_FRTB">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Approach_For_Prudential_Purposes"
        unique="false" eType="#//Approach_For_Prudential_Purposes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Base" unique="false" eType="#//Base"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Contingent_Scenario" unique="false"
        eType="#//Contingent_Scenario"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Delta_Vega_Or_Curvature_Risk"
        unique="false" eType="#//Delta_Vega_Or_Curvature_Risk"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Hypothetical_Value_Under_Specific_Assumptions"
        unique="false" eType="#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Instrument" unique="false"
        eType="#//Instrument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Main_Catagory" unique="false"
        eType="#//Main_Catagory"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Market_Risk_Portfolio"
        unique="false" eType="#//Market_Risk_Portfolio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Own_Funds_Requirements"
        unique="false" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Position_In_The_Instrument"
        unique="false" eType="#//Position_In_The_Instrument"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Prudentia_lPortfolio" unique="false"
        eType="#//Prudential_Portfolio"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Sensitivity_To_Delta_Risk_Factors"
        unique="false" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type_And_Nature_Of_Sensitivity"
        unique="false" eType="#//Type_And_Nature_Of_Sensitivity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type_Of_Risk" unique="false"
        eType="#//Type_Of_Risk"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Risk_factor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Risk_factor_Identifier"
        unique="false" eType="#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Risk_measure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Risk_measure_identifier"
        unique="false" eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theRisk_factor" lowerBound="1"
        eType="#//Risk_factor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theSecurity_or_exchange_tradable_derivative_position"
        lowerBound="1" eType="#//Security_or_exchange_tradable_derivative_position"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Shock_direction" unique="false"
        eType="#//ShockDirection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Curvature_valuation_difference"
        unique="false" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Curvature_risk_weight"
        unique="false" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Tenor" unique="false" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Delta_sensitivity" unique="false"
        eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="option_maturity" unique="false"
        eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Vega_sensitivity" unique="false"
        eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="underlying_residual_maturity"
        unique="false" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Currency_of_record" unique="false"
        eType="#//Currency"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Risk_measure_type" lowerBound="1"
        eType="#//Risk_measure_type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Securitisation" eSuperTypes="#//Security_issue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Securitisation_sector"
        unique="false" eType="#//Securitisation_sector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Securitisation_CTP_risk_factor_" eSuperTypes="#//Risk_factor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Securitisation_non_CTP_risk_factor"
      eSuperTypes="#//Risk_factor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Tranche_name" unique="false"
        eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theSecuritisation" lowerBound="1"
        eType="#//Securitisation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Security_issue" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Issue_Identifier" unique="false"
        eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Ratings_grade" unique="false"
        eType="#//Rating_grade"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theOrganisation" lowerBound="1"
        eType="#//Organisation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Security_or_exchange_tradable_derivative_position">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Position_identifier" unique="false"
        eType="#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Total_delta_sensitivity_per_bucket_derived">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Total_GIRR_delta_sensitivity_per_bucket"
        unique="false" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Total_GIRR_delta_sensitivity_squared_per_bucket"
        unique="false" eType="#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Total_sensitivities_bucket_identifier"
        unique="false" eType="#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theNetted_delta_sensitivities_per_risk_factor_and_tenor_deriveds"
        upperBound="-1" eType="#//Netted_delta_sensitivities_per_risk_factor_and_tenor_derived"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Approach_For_Prudential_Purposes">
    <eLiterals name="NA" value="1" literal="NA"/>
    <eLiterals name="Sensitivities_Based_Method" value="2" literal="Sensitivities_Based_Method"/>
    <eLiterals name="Method_To_Determine_The_Default_Risk_Charge" value="3" literal="Method_To_Determine_The_Default_Risk_Charge"/>
    <eLiterals name="Method_To_Determine_The_Residual_Risk_Charge" value="4" literal="Method_To_Determine_The_Residual_Risk_Charge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Base">
    <eLiterals name="NA" value="5" literal="NA"/>
    <eLiterals name="Memorandum_Items" value="6" literal="Memorandum_Items"/>
    <eLiterals name="Exposures" value="7" literal="Exposures"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Boolean"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Commodity_type">
    <eLiterals name="NA" value="8" literal="NA"/>
    <eLiterals name="Energy_solid_combustables" value="9" literal="Energy_solid_combustables"/>
    <eLiterals name="Softs_and_other_agriculturals" value="10" literal="Softs_and_other_agriculturals"/>
    <eLiterals name="Other_commodity" value="11" literal="Other_commodity"/>
    <eLiterals name="Energy_liquid_combustables" value="12" literal="Energy_liquid_combustables"/>
    <eLiterals name="Energy_electricity_and_carbon_trading" value="13" literal="Energy_electricity_and_carbon_trading"/>
    <eLiterals name="Freight" value="14" literal="Freight"/>
    <eLiterals name="Metals_non_precious" value="15" literal="Metals_non_precious"/>
    <eLiterals name="Gaseous_combustables" value="16" literal="Gaseous_combustables"/>
    <eLiterals name="Precious_metals" value="17" literal="Precious_metals"/>
    <eLiterals name="Grains_and_oilseed" value="18" literal="Grains_and_oilseed"/>
    <eLiterals name="Livestock_and_dairy" value="19" literal="Livestock_and_dairy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Contingent_Scenario">
    <eLiterals name="NA" value="20" literal="NA"/>
    <eLiterals name="Low_Correlation_Scenario" value="21" literal="Low_Correlation_Scenario"/>
    <eLiterals name="Medium_Correlation_Scenario" value="22" literal="Medium_Correlation_Scenario"/>
    <eLiterals name="High_Correlation_Scenario" value="23" literal="High_Correlation_Scenario"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CSR_curve_type">
    <eLiterals name="NA" value="24" literal="NA"/>
    <eLiterals name="Bond" value="25" literal="Bond"/>
    <eLiterals name="CDS" value="26" literal="CDS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Currency">
    <eLiterals name="NA" value="27" literal="NA"/>
    <eLiterals name="EUR" value="28" literal="EUR"/>
    <eLiterals name="JYP" value="29" literal="JYP"/>
    <eLiterals name="USD" value="30" literal="USD"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Delta_Vega_Or_Curvature_Risk">
    <eLiterals name="NA" value="31" literal="NA"/>
    <eLiterals name="Delta_Risk" value="32" literal="Delta_Risk"/>
    <eLiterals name="Vega_Risk" value="33" literal="Vega_Risk"/>
    <eLiterals name="Curvature_Risk" value="34" literal="Curvature_Risk"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Economy">
    <eLiterals name="NA" value="35" literal="NA"/>
    <eLiterals name="Emerging_market" value="36" literal="Emerging_market"/>
    <eLiterals name="Advanced_economy" value="37" literal="Advanced_economy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Equity_factor_type">
    <eLiterals name="NA" value="38" literal="NA"/>
    <eLiterals name="Spot" value="39" literal="Spot"/>
    <eLiterals name="Repo" value="40" literal="Repo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GIRR_risk_factor_type">
    <eLiterals name="NA" value="41" literal="NA"/>
    <eLiterals name="Inflation" value="42" literal="Inflation"/>
    <eLiterals name="Basis" value="43" literal="Basis"/>
    <eLiterals name="Yield" value="44" literal="Yield"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Instrument">
    <eLiterals name="NA" value="45" literal="NA"/>
    <eLiterals name="Instruments_Other_Than_Securitisation_Positions" value="46" literal="Instruments_Other_Than_Securitisation_Positions"/>
    <eLiterals name="Securitisation_Positions" value="47" literal="Securitisation_Positions"/>
    <eLiterals name="Instruments_With_Exotic_Underlyings" value="48" literal="Instruments_With_Exotic_Underlyings"/>
    <eLiterals name="Alternative_Correlation_Trading_Portfolio" value="49" literal="Alternative_Correlation_Trading_Portfolio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Main_Catagory">
    <eLiterals name="NA" value="50" literal="NA"/>
    <eLiterals name="Instruments_Subject_To_Market_Risk" value="51" literal="Instruments_Subject_To_Market_Risk"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Market_cap">
    <eLiterals name="NA" value="52" literal="NA"/>
    <eLiterals name="Large" value="53" literal="Large"/>
    <eLiterals name="Small" value="54" literal="Small"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Market_Risk_Portfolio">
    <eLiterals name="NA" value="55" literal="NA"/>
    <eLiterals name="Non_ACTP" value="56" literal="Non_ACTP"/>
    <eLiterals name="ACTP" value="57" literal="ACTP"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Number"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Position_In_The_Instrument">
    <eLiterals name="NA" value="58" literal="NA"/>
    <eLiterals name="Long_Position" value="59" literal="Long_Position"/>
    <eLiterals name="Short_Position" value="60" literal="Short_Position"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Prudential_Portfolio">
    <eLiterals name="NA" value="61" literal="NA"/>
    <eLiterals name="Trading_Book" value="62" literal="Trading_Book"/>
    <eLiterals name="Banking_And_Trading_Book" value="63" literal="Banking_And_Trading_Book"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Rating_grade">
    <eLiterals name="NA" value="64" literal="NA"/>
    <eLiterals name="Senior_IG" value="65" literal="Senior_IG"/>
    <eLiterals name="Non_senior_IG" value="66" literal="Non_senior_IG"/>
    <eLiterals name="High_yield" value="67" literal="High_yield"/>
    <eLiterals name="Non_rated" value="68" literal="Non_rated"/>
    <eLiterals name="IG" value="69" literal="IG"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Sector">
    <eLiterals name="NA" value="70" literal="NA"/>
    <eLiterals name="Sovereign" value="71" literal="Sovereign"/>
    <eLiterals name="Local_government" value="72" literal="Local_government"/>
    <eLiterals name="Financials" value="73" literal="Financials"/>
    <eLiterals name="Basic_materials" value="74" literal="Basic_materials"/>
    <eLiterals name="Consumer_goods" value="75" literal="Consumer_goods"/>
    <eLiterals name="Technology" value="76" literal="Technology"/>
    <eLiterals name="Health_care" value="77" literal="Health_care"/>
    <eLiterals name="Covered_bonds" value="78" literal="Covered_bonds"/>
    <eLiterals name="Other_sector" value="79" literal="Other_sector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Securitisation_sector">
    <eLiterals name="NA" value="80" literal="NA"/>
    <eLiterals name="RMBS_prime" value="81" literal="RMBS_prime"/>
    <eLiterals name="RMBS_mid_pirme" value="82" literal="RMBS_mid_pirme"/>
    <eLiterals name="RMBS_sub_prime" value="83" literal="RMBS_sub_prime"/>
    <eLiterals name="CMBS" value="84" literal="CMBS"/>
    <eLiterals name="ABS_student_loan" value="85" literal="ABS_student_loan"/>
    <eLiterals name="ABS_auto" value="86" literal="ABS_auto"/>
    <eLiterals name="CLO_non_CTP" value="87" literal="CLO_non_CTP"/>
    <eLiterals name="Other_securitisation_sector" value="88" literal="Other_securitisation_sector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ShockDirection">
    <eLiterals name="NA" value="89" literal="NA"/>
    <eLiterals name="Up" value="90" literal="Up"/>
    <eLiterals name="Down" value="91" literal="Down"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="String_up_to_60_characters_limited_to_letters__capital_and_low_cases___numbers__dash_and_underscore"/>
  <eClassifiers xsi:type="ecore:EEnum" name="String_up_to_60_characters_limited_to_letters__capital_and_low_cases___numbers__dash_and_underscore_1"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Type_And_Nature_Of_Sensitivity">
    <eLiterals name="NA" value="92" literal="NA"/>
    <eLiterals name="Positive_Sensitivity_Gross_Per_Risk_Class_Unweighted" value="93"
        literal="Positive_Sensitivity_Gross_Per_Risk_Class_Unweighted"/>
    <eLiterals name="Negative_Sensitivity_Gross_Per_Risk_Class_Unweighted" value="94"
        literal="Negative_Sensitivity_Gross_Per_Risk_Class_Unweighted"/>
    <eLiterals name="Sensitivity_Net_Per_Risk_Class_Unweighted" value="95" literal="Sensitivity_Net_Per_Risk_Class_Unweighted"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type_Of_Risk">
    <eLiterals name="NA" value="96" literal="NA"/>
    <eLiterals name="GIRR" value="97" literal="GIRR"/>
    <eLiterals name="Equity_Risk" value="98" literal="Equity_Risk"/>
    <eLiterals name="Foreign_Exchange_Risk" value="99" literal="Foreign_Exchange_Risk"/>
    <eLiterals name="Commodity_Risk" value="100" literal="Commodity_Risk"/>
    <eLiterals name="CSR" value="101" literal="CSR"/>
    <eLiterals name="Default_Risk" value="102" literal="Default_Risk"/>
    <eLiterals name="Residual_Risk" value="103" literal="Residual_Risk"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Unknown"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Double" instanceClassName="java.lang.Double"/>
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Risk_measure_type">
    <eLiterals name="Curvature"/>
    <eLiterals name="Delta_sensitivity" value="1"/>
    <eLiterals name="Vega_sensitivity" value="2"/>
  </eClassifiers>
</ecore:EPackage>
