/*
 * generated by Xtext 2.21.0
 */
package org.eclipse.efbt.aorta.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAortaScopeProvider extends DelegatingScopeProvider {
}
