<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="structural_change_test_definitions" nsURI="http://www.eclipse.org/structural_change_test_definitions"
    nsPrefix="structural_change_test_definitions">
  <eClassifiers xsi:type="ecore:EClass" name="StructuralChangeMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputStructures" upperBound="-1"
        eType="#//InputStructureSubtypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputDataStructures" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.efbt.aorta.model.output_data_structures/model/output_data_structures.ecore#//OutputDataStructure"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" eType="ecore:EClass ../../org.eclipse.efbt.aorta.model.functionality_breakdown/model/scenarios.ecore#//ScenarioSet"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralChangeTestDefinition" eSuperTypes="../../org.eclipse.efbt.aorta.model.test_definition/model/test_definition.ecore#//E2ETestDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="structuralChangeMapping"
        eType="#//StructuralChangeMapping"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenario" eType="ecore:EClass ../../org.eclipse.efbt.aorta.model.functionality_breakdown/model/scenarios.ecore#//Scenario"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputStructureSubtypes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputStructure" eType="ecore:EClass ../../org.eclipse.efbt.aorta.model.input_data_structures/model/input_data_structures.ecore#//InputDataStructure"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subTypeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralChangeMappingModule" eSuperTypes="../../org.eclipse.efbt.aorta.model.module_management/model/module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//StructuralChangeMapping" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralChangeTestDefinitionModule"
      eSuperTypes="../../org.eclipse.efbt.aorta.model.module_management/model/module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testDefinitions" upperBound="-1"
        eType="#//StructuralChangeTestDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputStructureSubtypesModule" eSuperTypes="../../org.eclipse.efbt.aorta.model.module_management/model/module_management.ecore#//Module"/>
</ecore:EPackage>
