/*
 * generated by Xtext 2.23.0
 */
package org.eclipse.efbt.cocason.dsl.cocason;

import org.eclipse.efbt.cocason.dsl.cocason.conversion.DATEValueConverter;

import org.eclipse.xtext.conversion.IValueConverterService;

import org.eclipse.xtext.naming.IQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CoCaSonRuntimeModule extends AbstractCoCaSonRuntimeModule {
	
    
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return DATEValueConverter.class;
    }
    

}
