/*
 * generated by Xtext 2.22.0
 */
package org.eclipse.efbt.cocason.eclipse_plugin.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class CoCaSonOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
