<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="generation_rules" nsURI="http://www.example.org/generation_rules"
    nsPrefix="generation_rules">
  <eAnnotations source="license">
    <details key="license" value="Copyright (c) 2021 Bird Software Solutions Ltd&#xA; All rights reserved. This file and the accompanying materials are made available under the terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at http://www.eclipse.org/legal/epl-v20.html&#xA;&#xA;SPDX-License-Identifier: EPL-2.0 &#xA;&#xA; Contributors:&#xA; Neil Mackenzie - initial API and implementation&#xD;"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="RulesForReport">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputLayerCube" eType="ecore:EClass ecore_lite.ecore#//ELClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulesForTable" upperBound="-1"
        eType="#//RulesForILTable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RulesForILTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulesForTablePart" upperBound="-1"
        eType="#//RuleForILTablePart" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputLayerTable" eType="ecore:EClass ecore_lite.ecore#//ELClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="asAttribute" eType="ecore:EClass ecore_lite.ecore#//ELPublicOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectColumnMemberAs" eSuperTypes="#//SelectColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberAsConstant" eType="ecore:EClass ecore_lite.ecore#//ELEnumLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectColumnAttributeAs" eSuperTypes="#//SelectColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass ecore_lite.ecore#//ELAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectDerivedColumnAs" eSuperTypes="#//SelectColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass ecore_lite.ecore#//ELPublicOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectValueAs" eSuperTypes="#//SelectColumn">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Comparitor">
    <eLiterals name="less_than"/>
    <eLiterals name="equals" value="1"/>
    <eLiterals name="greater_than" value="2"/>
    <eLiterals name="not_equals" value="3" literal="not_equals"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableFilter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="predicate" eType="#//Predicate"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenerationRulesModule" eSuperTypes="module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulesForReport" upperBound="-1"
        eType="#//RulesForReport" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleForILTablePart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//SelectColumn" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whereClause" upperBound="-1"
        eType="#//TableFilter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Predicate" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndPredicate" eSuperTypes="#//Predicate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operands" upperBound="-1"
        eType="#//Predicate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrPredicate" eSuperTypes="#//Predicate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operands" upperBound="-1"
        eType="#//Predicate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotPredicate" eSuperTypes="#//Predicate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" eType="#//Predicate"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributePredicate" eSuperTypes="#//Predicate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute1" eType="ecore:EClass ecore_lite.ecore#//ELAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparitor" eType="#//Comparitor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" eType="ecore:EClass ecore_lite.ecore#//ELEnumLiteral"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
