<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="reports" nsURI="http://www.eclipse.org/efbt/reports" nsPrefix="reports">
  <eAnnotations source="license">
    <details key="license" value="Copyright (c) 2020 Bird Software Solutions Ltd&#xA; All rights reserved. This file and the accompanying materials are made available under the terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at http://www.eclipse.org/legal/epl-v20.html&#xA;&#xA;SPDX-License-Identifier: EPL-2.0 &#xA;&#xA; Contributors:&#xA; Neil Mackenzie - initial API and implementation&#xD;"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Report">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputLayer" eType="ecore:EClass ecore_lite.ecore#//ELClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//ReportRow"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//ReportColumn" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CellBasedReport" eSuperTypes="#//Report">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reportCells" upperBound="-1"
        eType="#//ReportCell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportRow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportColumn">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportCell">
    <eStructuralFeatures xsi:type="ecore:EReference" name="row" eType="#//ReportRow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" eType="#//ReportColumn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" upperBound="-1"
        eType="#//Filter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metric" eType="ecore:EClass ecore_lite.ecore#//ELOperation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datapointID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Filter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputLayer" eType="ecore:EClass ecore_lite.ecore#//ELClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="ecore:EClass ecore_lite.ecore#//ELOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" upperBound="-1"
        eType="ecore:EClass ecore_lite.ecore#//ELEnumLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportModule" eSuperTypes="module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reports" upperBound="-1"
        eType="#//Report" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RowColumnBasedReport" eSuperTypes="#//Report">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnFilters" upperBound="-1"
        eType="#//ColumnFilters" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rowFilters" upperBound="-1"
        eType="#//RowFilters" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wholeReportFilters" eType="#//WholeReportFilters"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RowFilters">
    <eStructuralFeatures xsi:type="ecore:EReference" name="row" eType="#//ReportRow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" upperBound="-1"
        eType="#//Filter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metric" eType="ecore:EClass ecore_lite.ecore#//ELOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnFilters">
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" eType="#//ReportColumn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" upperBound="-1"
        eType="#//Filter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metric" eType="ecore:EClass ecore_lite.ecore#//ELOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WholeReportFilters">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" upperBound="-1"
        eType="#//Filter" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
