<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="reports" nsURI="http://www.eclipse.org/efbt/reports" nsPrefix="reports">
  <eClassifiers xsi:type="ecore:EClass" name="Report">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputLayer" eType="ecore:EClass ecore_lite.ecore#//ELClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//ReportRow"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//ReportColumn" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reportCells" upperBound="-1"
        eType="#//ReportCell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportRow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportColumn">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportCell">
    <eStructuralFeatures xsi:type="ecore:EReference" name="row" eType="#//ReportRow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" eType="#//ReportColumn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" upperBound="-1"
        eType="#//Filter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metric" eType="ecore:EClass ecore_lite.ecore#//ELOperation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datapointID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Filter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputLayer" eType="ecore:EClass ecore_lite.ecore#//ELClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="ecore:EClass ecore_lite.ecore#//ELOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" upperBound="-1"
        eType="ecore:EClass ecore_lite.ecore#//ELEnumLiteral"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportModule" eSuperTypes="module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reports" upperBound="-1"
        eType="#//Report" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
