/*
 * generated by Xtext 2.21.0
 */
package org.eclipse.efbt.aorta;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AortaRuntimeModule extends AbstractAortaRuntimeModule {
}
