/*
 * generated by Xtext 2.22.0
 */
package org.eclipse.efbt.chirp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ChirpUiModule extends AbstractChirpUiModule {

	public ChirpUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
