/*
 * generated by Xtext 2.22.0
 */
package org.eclipse.efbt.chirp.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ChirpAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/eclipse/efbt/chirp/parser/antlr/internal/InternalChirp.tokens");
	}
}
