<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test_input_data" nsURI="http://www.eclipse.org/test_input_data"
    nsPrefix="test_input_data">
  <eClassifiers xsi:type="ecore:EClass" name="StructuredFile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fileSchema" eType="#//StructuredFileSchema"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuredFileSchema"/>
  <eClassifiers xsi:type="ecore:EClass" name="InputDataModule" eSuperTypes="../../org.eclipse.efbt.oa4rr.model.module_management/model/module_management.ecore#//Module">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="InputDataModule"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A module containeing a set of input data"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputData" upperBound="-1"
        eType="#//TestInputData" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="inputData"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The input data that makes up the module"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UsefulInputDataSnippets">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testInputData" eType="#//TestInputData"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestInputData">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="InputData"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="InputData for a test"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="name"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name associated with the input data."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalTestData"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestColumnStructuredData" eSuperTypes="#//TestInputData">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceTableData" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.efbt.oa4rr.model.column_structured_data/model/base_column_structured_data.ecore#//BaseColumnStructuredData"
        containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="sourceTableData"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The set of pupulated BaseCubes that represent the input data."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestStrucuredFileData" eSuperTypes="#//TestInputData">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testFileData" upperBound="-1"
        eType="#//StructuredFile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UsefulInputDataSnippetsModule" eSuperTypes="../../org.eclipse.efbt.oa4rr.model.module_management/model/module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="snippets" upperBound="-1"
        eType="#//UsefulInputDataSnippets" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
