<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test_worked_example" nsURI="http://www.eclipse.org/test_worked_example"
    nsPrefix="test_worked_example">
  <eClassifiers xsi:type="ecore:EClass" name="TestWithWorkedExample" eSuperTypes="test.ecore#//Test">
    <eStructuralFeatures xsi:type="ecore:EReference" name="workedExample" eType="ecore:EClass ../../org.eclipse.efbt.oa4rtt.model.spreadsheet_lineage/model/data_lineage.ecore#//SpreadsheetLineageModel"/>
  </eClassifiers>
</ecore:EPackage>
