<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="advanced_variable_lineagefunctions" nsURI="http://www.eclipse.org/advanced_variable_lineagefunctions"
    nsPrefix="advanced_variable_lineagefunctions">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel"/>
  <eAnnotations source="license">
    <details key="license" value="Copyright (c) 2020 Bird Software Solutions Ltd&#xA; All rights reserved. This file and the accompanying materials are made available under the terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at http://www.eclipse.org/legal/epl-v20.html&#xA;&#xA;SPDX-License-Identifier: EPL-2.0 &#xA;&#xA; Contributors:&#xA; Neil Mackenzie - initial API and implementation&#xD;"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="GetStructColumnFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnInStruct" eType="ecore:EClass ../../org.eclipse.efbt.cocamo.smcubes.model.core/model/core.ecore#//VARIABLE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cubeColumn" eType="ecore:EClass lineagefunctions.ecore#//CubeColumn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cube" eType="ecore:EClass ../../org.eclipse.efbt.lineage.common.model.lineagecubes/model/cubes.ecore#//FreeBirdToolsCube"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usedInSubset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResolvedStructColumnParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnInsideStruct" eType="ecore:EClass ../../org.eclipse.efbt.cocamo.smcubes.model.core/model/core.ecore#//VARIABLE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cubeColumn" eType="ecore:EClass lineagefunctions.ecore#//CubeColumn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpeculativeStructColumnParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnInsideStruct" eType="ecore:EClass ../../org.eclipse.efbt.cocamo.smcubes.model.core/model/core.ecore#//VARIABLE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cube" eType="ecore:EClass ../../org.eclipse.efbt.lineage.common.model.lineagecubes/model/cubes.ecore#//FreeBirdToolsCube"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structColumn" eType="ecore:EClass ../../org.eclipse.efbt.lineage.common.model.lineagecubes/model/efbt_advanced_data_definition.ecore#//StructTypedVariable"/>
  </eClassifiers>
</ecore:EPackage>
