<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="program" nsURI="http://www.eclipse.org/efbt/program" nsPrefix="program">
  <eAnnotations source="license">
    <details key="license" value="Copyright (c) 2020 Bird Software Solutions Ltd&#xA; All rights reserved. This file and the accompanying materials are made available under the terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at http://www.eclipse.org/legal/epl-v20.html&#xA;&#xA;SPDX-License-Identifier: EPL-2.0 &#xA;&#xA; Contributors:&#xA; Neil Mackenzie - initial API and implementation&#xD;"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="This Package describes the grouping of artifacts for CoCaMo for SMCubes into a Program. &#xA;A program relates to the group of artifacts, and we allow the contents of  Programs to reference other programs.&#xA;"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SMCubesStaticModel" eSuperTypes="#//StaticModel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An SMCubesStaticModel  relates to the group of artifacts, and we allow the contents of  a SMCubesStaticModel  to reference other SMCubesStaticModels.&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="smCubesModel" eType="ecore:EClass ../../org.eclipse.efbt.cocalimo.smcubes.model.core/model/smcubes_model.ecore#//SmcubesModel">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The SMCubes Model associated with the Program"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" eType="ecore:EClass ../../org.eclipse.efbt.cocalimo.core.model.requirements_text/model/requirements_text.ecore#//RequirementsModule">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The requirements associated with the program, these will be refrence by Tasks"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bddTestDefinitions" eType="ecore:EClass ../../org.eclipse.efbt.cocalimo.core.model.testing/model/test_definition.ecore#//BDDTestDefinitionModule">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The TestDefinitions associated with the program, these will be refrence by Tasks"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tests" eType="#//SMCubesBDDTestModule">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Tests associated with the program, these will be refrence by Tasks"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testTemplates" eType="ecore:EClass ../../org.eclipse.efbt.cocalimo.core.model.testing/model/test_definition.ecore#//BDDTestTemplateModule">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The TestTemplates associated with the program, these will be refrence by Tasks"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testConstriants" eType="ecore:EClass ../../org.eclipse.efbt.cocalimo.core.model.testing/model/test_definition.ecore#//BDDTestContraints">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The TestConstraints associated with the program, these will be refrence by Tasks"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionalityModules" eType="ecore:EClass ../../org.eclipse.efbt.cocalimo.core.model.task/model/task.ecore#//TaskModule">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The FunctionaltyModules associated with the program, these will be refrence by Tasks"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regFunctionalityTests"
        eType="#//SMCubesRegFunctionalityTestModule">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Tests associated with the program, these will be refrence by Tasks"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regFunctionalityTestDefinitions"
        eType="ecore:EClass ../../org.eclipse.efbt.cocalimo.core.model.testing/model/test_definition.ecore#//RegFunctionalityTestDefinitionModule">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The TestDefinitions associated with the program, these will be refrence by Tasks"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMCubesTestInputData" eSuperTypes="../../org.eclipse.efbt.cocalimo.core.model.testing/model/test_input_data.ecore#//TestInputData">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="InputData for that represents instances of SMCubesModels, they are set of rws of data meeting the cube structure of an associated cube"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="smcubes_inputdata" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.efbt.cocalimo.smcubes.model.input_data/model/base_column_structured_data.ecore#//BaseColumnStructuredData"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The input data"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMCubesReportResults" eSuperTypes="../../org.eclipse.efbt.cocalimo.core.model.testing/model/test.ecore#//Result">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Expected results which follwo the way that SMCubes represents Report Celss (As COMBINATIONs)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reportCells" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.efbt.cocalimo.smcubes.model.core/model/reports.ecore#//ReportCellValue"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The value of a ReportCell"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMCubesBDDTest" eSuperTypes="../../org.eclipse.efbt.cocalimo.core.model.testing/model/test.ecore#//BDDTest">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A test specific to the SMCubes methodolgy of describing Input Data structures and Output DataStructures (As cubes of typically COMBINATIONS representing report cells)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputData" eType="#//SMCubesTestInputData"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The input data"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expectedResults" eType="#//SMCubesReportResults"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The expected results"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMCubesBDDTestModule" eSuperTypes="../../org.eclipse.efbt.cocalimo.core.model.testing/model/test.ecore#//TestModule">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A module containing a set of SMCubesTests"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tests" upperBound="-1"
        eType="#//SMCubesBDDTest" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The tests"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticModel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A StaticModel relates to the group of artifacts, and we allow the contents of  a StaticModel to reference other StaticModels.&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMCubesRegFunctionalityTest" eSuperTypes="../../org.eclipse.efbt.cocalimo.core.model.testing/model/test.ecore#//RegFunctionalityTest">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputData" eType="#//SMCubesTestInputData"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The input data"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expectedResults" eType="#//SMCubesReportResults"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The expected results"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SMCubesRegFunctionalityTestModule" eSuperTypes="../../org.eclipse.efbt.cocalimo.core.model.testing/model/test.ecore#//TestModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="regFunctionalityTests"
        upperBound="-1" eType="#//SMCubesRegFunctionalityTest" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
