<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bpmn_lite" nsURI="http://www.eclipse.org/efbt/bpmn_lite" nsPrefix="bpmn_lite">
  <eAnnotations source="license">
    <details key="license" value="Copyright (c) 2020 Bird Software Solutions Ltd&#xA; All rights reserved. This file and the accompanying materials are made available under the terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at http://www.eclipse.org/legal/epl-v20.html&#xA;&#xA;SPDX-License-Identifier: EPL-2.0 &#xA;&#xA; Contributors:&#xA; Neil Mackenzie - initial API and implementation&#xD;"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="BaseElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invisible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowElementsContainer" abstract="true"
      eSuperTypes="#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="flowElements" ordered="false"
        upperBound="-1" eType="#//FlowElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowElement" abstract="true" eSuperTypes="#//BaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowNode" abstract="true" eSuperTypes="#//FlowElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//SequenceFlow" eOpposite="#//SequenceFlow/sourceRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" ordered="false"
        upperBound="-1" eType="#//SequenceFlow" eOpposite="#//SequenceFlow/targetRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attr1" eType="ecore:EClass ecore_lite.ecore#//ELAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparison" eType="#//AttrComparison"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" eType="ecore:EClass ecore_lite.ecore#//ELEnumLiteral"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AttrComparison">
    <eLiterals name="equals"/>
    <eLiterals name="less_than" value="1"/>
    <eLiterals name="greater_than" value="2"/>
    <eLiterals name="not_equals" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceFlow" eSuperTypes="#//FlowElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetRef" ordered="false"
        eType="#//FlowNode" eOpposite="#//FlowNode/incoming"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceRef" ordered="false"
        eType="#//FlowNode" eOpposite="#//FlowNode/outgoing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//Activity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" abstract="true" eSuperTypes="#//FlowNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Gateway" abstract="true" eSuperTypes="#//FlowNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExclusiveGateway" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="InclusiveGateway" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelGateway" eSuperTypes="#//Gateway"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enrichedAttribute" eType="ecore:EClass ecore_lite.ecore#//ELOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
        eType="#//Scenario" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secondAttribute" eType="ecore:EClass ecore_lite.ecore#//ELAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredAttributesForScenarioChoice"
        upperBound="-1" eType="ecore:EClass ecore_lite.ecore#//ELAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entityCreationTask" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredAttributesForEntityCreation"
        upperBound="-1" eType="ecore:EClass ecore_lite.ecore#//ELAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubProcess" eSuperTypes="#//Activity #//FlowElementsContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScriptTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectionLayers" upperBound="-1"
        eType="#//SelectionLayer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputLayer" eType="ecore:EClass ecore_lite.ecore#//ELClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserTask" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="ecore:EClass ecore_lite.ecore#//ELClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityTag" eSuperTypes="requirements_text.ecore#//Tag">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Scenario"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Scenario"/>
      <details key="kind" value="empty"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name of the Scenario"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="name"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invisible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name of the Scenario"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="description"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredAttributes" upperBound="-1"
        eType="ecore:EClass ecore_lite.ecore#//ELAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data_constraints" eType="#//DataConstraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScenarioTag" eSuperTypes="requirements_text.ecore#//Tag">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Tag which tags a Scenario in order to link it with requirements."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenario" eType="#//Scenario">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The tagged Scenario."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowModule" eSuperTypes="module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskTags" upperBound="-1"
        eType="#//ActivityTag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioTags" upperBound="-1"
        eType="#//ScenarioTag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subProcess" upperBound="-1"
        eType="#//SubProcess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectionLayer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invisible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedEntity" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
</ecore:EPackage>
