<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="logical_transformations" nsURI="http://www.eclipse.org/efbt/logical_transformations"
    nsPrefix="logical_transformations">
  <eClassifiers xsi:type="ecore:EClass" name="LogicalTransformationModule" eSuperTypes="../../org.eclipse.efbt.cocalimo.core.model.module_management/model/module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskTags" upperBound="-1"
        eType="#//TaskTag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioTags" upperBound="-1"
        eType="ecore:EClass scenarios.ecore#//ScenarioTag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioSetTags" upperBound="-1"
        eType="ecore:EClass scenarios.ecore#//ScenarioSetTag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subProcesses" upperBound="-1"
        eType="ecore:EClass bpmn_lite.ecore#//SubProcess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskTag" eSuperTypes="../../org.eclipse.efbt.cocalimo.core.model.requirements_text/model/requirements_text.ecore#//Tag"/>
</ecore:EPackage>
