<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="deep_structures" nsURI="http://www.eclipse.org/deep_structures"
    nsPrefix="deep_structures">
  <eClassifiers xsi:type="ecore:EClass" name="DeepStructureDefinitionProxy" eSuperTypes="../../org.eclipse.efbt.aorta.model.input_data_structures/model/input_data_structures.ecore#//InputDataStructure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="structureDefinitionID"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeepStructureDefinitionProxyModule"
      eSuperTypes="../../org.eclipse.efbt.aorta.model.input_data_structures/model/input_data_structures.ecore#//InputDatastructureModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="structures" upperBound="-1"
        eType="#//DeepStructureDefinitionProxy" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
