/*
 * generated by Xtext
 */
package org.eclipse.emf.eson.xtextintegration.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.emf.eson.xtextintegration.ui.internal.MyDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MyDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MyDslActivator.getInstance().getInjector(MyDslActivator.ORG_ECLIPSE_EMF_ESON_XTEXTINTEGRATION_MYDSL);
	}
	
}
