<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="execution_environments" nsURI="http://www.eclipse.org/execution_environments"
    nsPrefix="execution_environments">
  <eClassifiers xsi:type="ecore:EClass" name="TestExecutionEnvironment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executableLogic" eType="ecore:EClass ../../org.eclipse.efbt.oa4rtt.model.executablelogic/model/executable_logic.ecore#//ExecutableLogicModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnStructures" eType="ecore:EClass ../../org.eclipse.efbt.oa4rtt.model.column_structures/model/column_structures.ecore#//ColumnStructureModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reportsModule" eType="ecore:EClass ../../org.eclipse.efbt.oa4rtt.model.report_structures/model/report_structures.ecore#//RegReportModule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestExecutionEnvironmentModule" eSuperTypes="../../org.eclipse.efbt.oa4rtt.model.module_management/model/module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testexecutionEnvironments"
        eType="#//TestExecutionEnvironment" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
