/*
 * generated by Xtext 2.23.0
 */
package org.eclipse.efbt.cocason.eclipse_plugin.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.efbt.cocason.eclipse_plugin.CoCaSonRuntimeModule;
import org.eclipse.efbt.cocason.eclipse_plugin.CoCaSonStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CoCaSonIdeSetup extends CoCaSonStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CoCaSonRuntimeModule(), new CoCaSonIdeModule()));
	}
	
}
