<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sql_lite" nsURI="http://www.example.org/sql_lite" nsPrefix="sql_lite">
  <eClassifiers xsi:type="ecore:EClass" name="View" eSuperTypes="#//SQLEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectClause" eType="#//SelectClause"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromClause" eType="#//FromClause"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whereClause" eType="#//WhereClause"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//SelectColumn" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectColumn" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="as" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnAsFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//ETypedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhereClause"/>
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//SQLEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="ecore:EClass ../../org.eclipse.efbt.cocalimo.smcubes.model.core/model/data_meta_model.ecore#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SQLEntity"/>
  <eClassifiers xsi:type="ecore:EClass" name="FromClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sqlEntities" eType="#//SQLEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SQLEntityModule" eSuperTypes="../../org.eclipse.efbt.cocalimo.core.model.module_management/model/module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sqlEntities" upperBound="-1"
        eType="#//SQLEntity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratedEntitySQL">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedEntity" eType="ecore:EClass ../../org.eclipse.efbt.cocalimo.smcubes.model.core/model/data_meta_model.ecore#//GeneratedEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="view" eType="#//View"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratedEntitySQLModule" eSuperTypes="../../org.eclipse.efbt.cocalimo.core.model.module_management/model/module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="GeneratedEntitySQLs" upperBound="-1"
        eType="#//GeneratedEntitySQL" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
