/*
 * generated by Xtext
 */
package org.eclipse.emf.eson.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class EFactoryGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class FactoryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.Factory");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cImportsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cImportsNamespaceImportParserRuleCall_0_0 = (RuleCall)cImportsAssignment_0.eContents().get(0);
		private final Assignment cEPackagesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cEPackagesPackageImportParserRuleCall_1_0 = (RuleCall)cEPackagesAssignment_1.eContents().get(0);
		private final Assignment cAnnotationsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAnnotationsAnnotationParserRuleCall_2_0 = (RuleCall)cAnnotationsAssignment_2.eContents().get(0);
		private final Assignment cRootAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cRootNewObjectParserRuleCall_3_0 = (RuleCall)cRootAssignment_3.eContents().get(0);
		
		//Factory:
		//	imports+=NamespaceImport*
		//	ePackages+=PackageImport*
		//	annotations+=Annotation*
		//	root=NewObject;
		@Override public ParserRule getRule() { return rule; }

		//imports+=NamespaceImport* ePackages+=PackageImport* annotations+=Annotation* root=NewObject
		public Group getGroup() { return cGroup; }

		//imports+=NamespaceImport*
		public Assignment getImportsAssignment_0() { return cImportsAssignment_0; }

		//NamespaceImport
		public RuleCall getImportsNamespaceImportParserRuleCall_0_0() { return cImportsNamespaceImportParserRuleCall_0_0; }

		//ePackages+=PackageImport*
		public Assignment getEPackagesAssignment_1() { return cEPackagesAssignment_1; }

		//PackageImport
		public RuleCall getEPackagesPackageImportParserRuleCall_1_0() { return cEPackagesPackageImportParserRuleCall_1_0; }

		//annotations+=Annotation*
		public Assignment getAnnotationsAssignment_2() { return cAnnotationsAssignment_2; }

		//Annotation
		public RuleCall getAnnotationsAnnotationParserRuleCall_2_0() { return cAnnotationsAnnotationParserRuleCall_2_0; }

		//root=NewObject
		public Assignment getRootAssignment_3() { return cRootAssignment_3; }

		//NewObject
		public RuleCall getRootNewObjectParserRuleCall_3_0() { return cRootNewObjectParserRuleCall_3_0; }
	}

	public class PackageImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.PackageImport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cEPackageAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cEPackageEPackageCrossReference_1_0 = (CrossReference)cEPackageAssignment_1.eContents().get(0);
		private final RuleCall cEPackageEPackageStringOrQualifiedNameWithWildcardParserRuleCall_1_0_1 = (RuleCall)cEPackageEPackageCrossReference_1_0.eContents().get(1);
		
		//PackageImport:
		//	'use' ePackage=[ecore::EPackage|StringOrQualifiedNameWithWildcard];
		@Override public ParserRule getRule() { return rule; }

		//'use' ePackage=[ecore::EPackage|StringOrQualifiedNameWithWildcard]
		public Group getGroup() { return cGroup; }

		//'use'
		public Keyword getUseKeyword_0() { return cUseKeyword_0; }

		//ePackage=[ecore::EPackage|StringOrQualifiedNameWithWildcard]
		public Assignment getEPackageAssignment_1() { return cEPackageAssignment_1; }

		//[ecore::EPackage|StringOrQualifiedNameWithWildcard]
		public CrossReference getEPackageEPackageCrossReference_1_0() { return cEPackageEPackageCrossReference_1_0; }

		//StringOrQualifiedNameWithWildcard
		public RuleCall getEPackageEPackageStringOrQualifiedNameWithWildcardParserRuleCall_1_0_1() { return cEPackageEPackageStringOrQualifiedNameWithWildcardParserRuleCall_1_0_1; }
	}

	public class NamespaceImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.NamespaceImport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportedNamespaceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0 = (RuleCall)cImportedNamespaceAssignment_1.eContents().get(0);
		
		//NamespaceImport:
		//	'import' importedNamespace=QualifiedNameWithWildcard
		//	// TODO Content Assist for EPackage .. but one COULD also import other named NewObject / EObject, instead of EPackages.. hm. As EPackage will be much more common, just support that.	
		//;
		@Override public ParserRule getRule() { return rule; }

		//'import' importedNamespace=QualifiedNameWithWildcard
		public Group getGroup() { return cGroup; }

		//'import'
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }

		//importedNamespace=QualifiedNameWithWildcard
		public Assignment getImportedNamespaceAssignment_1() { return cImportedNamespaceAssignment_1; }

		//QualifiedNameWithWildcard
		public RuleCall getImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0() { return cImportedNamespaceQualifiedNameWithWildcardParserRuleCall_1_0; }
	}

	public class AnnotationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.Annotation");
		private final RuleCall cCustomNameMappingParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Annotation:
		//	CustomNameMapping;
		@Override public ParserRule getRule() { return rule; }

		//CustomNameMapping
		public RuleCall getCustomNameMappingParserRuleCall() { return cCustomNameMappingParserRuleCall; }
	}

	public class CustomNameMappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.CustomNameMapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cEClassAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cEClassEClassCrossReference_2_0 = (CrossReference)cEClassAssignment_2.eContents().get(0);
		private final RuleCall cEClassEClassQualifiedNameParserRuleCall_2_0_1 = (RuleCall)cEClassEClassCrossReference_2_0.eContents().get(1);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameFeatureAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cNameFeatureEAttributeCrossReference_4_0 = (CrossReference)cNameFeatureAssignment_4.eContents().get(0);
		private final RuleCall cNameFeatureEAttributeQualifiedNameParserRuleCall_4_0_1 = (RuleCall)cNameFeatureEAttributeCrossReference_4_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//// TODO further consider if name mapping is best put in-line into objects.. it would have to repeat in every file..
		//// logically this rather belongs into an external mapping, like HUTN's Configuration (HutnConfig), or even better directly into an Xcore as annotations 
		//CustomNameMapping:
		//	"@Name" "{" eClass=[ecore::EClass|QualifiedName] "=" nameFeature=[ecore::EAttribute|QualifiedName] "}";
		@Override public ParserRule getRule() { return rule; }

		//"@Name" "{" eClass=[ecore::EClass|QualifiedName] "=" nameFeature=[ecore::EAttribute|QualifiedName] "}"
		public Group getGroup() { return cGroup; }

		//"@Name"
		public Keyword getNameKeyword_0() { return cNameKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//eClass=[ecore::EClass|QualifiedName]
		public Assignment getEClassAssignment_2() { return cEClassAssignment_2; }

		//[ecore::EClass|QualifiedName]
		public CrossReference getEClassEClassCrossReference_2_0() { return cEClassEClassCrossReference_2_0; }

		//QualifiedName
		public RuleCall getEClassEClassQualifiedNameParserRuleCall_2_0_1() { return cEClassEClassQualifiedNameParserRuleCall_2_0_1; }

		//"="
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }

		//nameFeature=[ecore::EAttribute|QualifiedName]
		public Assignment getNameFeatureAssignment_4() { return cNameFeatureAssignment_4; }

		//[ecore::EAttribute|QualifiedName]
		public CrossReference getNameFeatureEAttributeCrossReference_4_0() { return cNameFeatureEAttributeCrossReference_4_0; }

		//QualifiedName
		public RuleCall getNameFeatureEAttributeQualifiedNameParserRuleCall_4_0_1() { return cNameFeatureEAttributeQualifiedNameParserRuleCall_4_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class FeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.Feature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cEFeatureAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cEFeatureEStructuralFeatureCrossReference_0_0 = (CrossReference)cEFeatureAssignment_0.eContents().get(0);
		private final RuleCall cEFeatureEStructuralFeatureQualifiedNameParserRuleCall_0_0_1 = (RuleCall)cEFeatureEStructuralFeatureCrossReference_0_0.eContents().get(1);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueValueParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//Feature:
		//	eFeature=[ecore::EStructuralFeature|QualifiedName] ":" value=Value?;
		@Override public ParserRule getRule() { return rule; }

		//eFeature=[ecore::EStructuralFeature|QualifiedName] ":" value=Value?
		public Group getGroup() { return cGroup; }

		//eFeature=[ecore::EStructuralFeature|QualifiedName]
		public Assignment getEFeatureAssignment_0() { return cEFeatureAssignment_0; }

		//[ecore::EStructuralFeature|QualifiedName]
		public CrossReference getEFeatureEStructuralFeatureCrossReference_0_0() { return cEFeatureEStructuralFeatureCrossReference_0_0; }

		//QualifiedName
		public RuleCall getEFeatureEStructuralFeatureQualifiedNameParserRuleCall_0_0_1() { return cEFeatureEStructuralFeatureQualifiedNameParserRuleCall_0_0_1; }

		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }

		//value=Value?
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//Value
		public RuleCall getValueValueParserRuleCall_2_0() { return cValueValueParserRuleCall_2_0; }
	}

	public class NewObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.NewObject");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cEClassAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cEClassEClassCrossReference_0_0 = (CrossReference)cEClassAssignment_0.eContents().get(0);
		private final RuleCall cEClassEClassQualifiedNameParserRuleCall_0_0_1 = (RuleCall)cEClassEClassCrossReference_0_0.eContents().get(1);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameValidIDParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFeaturesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFeaturesFeatureParserRuleCall_3_0 = (RuleCall)cFeaturesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//// Re. use of QualifiedName, see SimplestWeiredNameTest (we want to permit EAttribute name to have dots; strange yes, but due to a particular requirement in an in-house closed source product)
		//// Also value isn't really optional semantically of course
		//// but because it may be missing while typing, this works out much better in practice like this
		//// the EFactoryJavaValidator flags it up if it's really missing
		//// without this, there are confusing parsing errors, the proposal provider doesn't work as it should, etc.
		//NewObject:
		//	eClass=[ecore::EClass|QualifiedName] name=ValidID? "{"
		//	features+=Feature*
		//	"}";
		@Override public ParserRule getRule() { return rule; }

		//// Note that this is also in-lined below; if making changes, adapt below too
		//eClass=[ecore::EClass|QualifiedName] name=ValidID? "{" features+=Feature* "}"
		public Group getGroup() { return cGroup; }

		//// Note that this is also in-lined below; if making changes, adapt below too
		//eClass=[ecore::EClass|QualifiedName]
		public Assignment getEClassAssignment_0() { return cEClassAssignment_0; }

		//[ecore::EClass|QualifiedName]
		public CrossReference getEClassEClassCrossReference_0_0() { return cEClassEClassCrossReference_0_0; }

		//QualifiedName
		public RuleCall getEClassEClassQualifiedNameParserRuleCall_0_0_1() { return cEClassEClassQualifiedNameParserRuleCall_0_0_1; }

		//name=ValidID?
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ValidID
		public RuleCall getNameValidIDParserRuleCall_1_0() { return cNameValidIDParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//features+=Feature*
		public Assignment getFeaturesAssignment_3() { return cFeaturesAssignment_3; }

		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_3_0() { return cFeaturesFeatureParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class ValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.Value");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMultiValueParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAttributeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cGroup_2.eContents().get(0);
		private final Group cGroup_2_0_0 = (Group)cGroup_2_0.eContents().get(0);
		private final Action cNewObjectAction_2_0_0_0 = (Action)cGroup_2_0_0.eContents().get(0);
		private final Assignment cEClassAssignment_2_0_0_1 = (Assignment)cGroup_2_0_0.eContents().get(1);
		private final CrossReference cEClassEClassCrossReference_2_0_0_1_0 = (CrossReference)cEClassAssignment_2_0_0_1.eContents().get(0);
		private final RuleCall cEClassEClassQualifiedNameParserRuleCall_2_0_0_1_0_1 = (RuleCall)cEClassEClassCrossReference_2_0_0_1_0.eContents().get(1);
		private final Assignment cNameAssignment_2_0_0_2 = (Assignment)cGroup_2_0_0.eContents().get(2);
		private final RuleCall cNameValidIDParserRuleCall_2_0_0_2_0 = (RuleCall)cNameAssignment_2_0_0_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2_0_0_3 = (Keyword)cGroup_2_0_0.eContents().get(3);
		private final Assignment cFeaturesAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cFeaturesFeatureParserRuleCall_2_1_0 = (RuleCall)cFeaturesAssignment_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Action cContainmentValueAction_2_3 = (Action)cGroup_2.eContents().get(3);
		private final RuleCall cReferenceParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Value:
		//	MultiValue
		//	| Attribute | // Following is an in-lined NewObject, if making changes, adapt above too
		//	=> ({NewObject} eClass=[ecore::EClass|QualifiedName]? name=ValidID? "{") features+=Feature*
		//	"}" {Containment.value=current} | => Reference;
		@Override public ParserRule getRule() { return rule; }

		//MultiValue | Attribute | // Following is an in-lined NewObject, if making changes, adapt above too
		//=> ({NewObject} eClass=[ecore::EClass|QualifiedName]? name=ValidID? "{") features+=Feature* "}"
		//{Containment.value=current} | => Reference
		public Alternatives getAlternatives() { return cAlternatives; }

		//MultiValue
		public RuleCall getMultiValueParserRuleCall_0() { return cMultiValueParserRuleCall_0; }

		//Attribute
		public RuleCall getAttributeParserRuleCall_1() { return cAttributeParserRuleCall_1; }

		//=> ({NewObject} eClass=[ecore::EClass|QualifiedName]? name=ValidID? "{") features+=Feature* "}"
		//{Containment.value=current}
		public Group getGroup_2() { return cGroup_2; }

		//// Following is an in-lined NewObject, if making changes, adapt above too
		//=> ({NewObject} eClass=[ecore::EClass|QualifiedName]? name=ValidID? "{")
		public Group getGroup_2_0() { return cGroup_2_0; }

		//({NewObject} eClass=[ecore::EClass|QualifiedName]? name=ValidID? "{")
		public Group getGroup_2_0_0() { return cGroup_2_0_0; }

		//{NewObject}
		public Action getNewObjectAction_2_0_0_0() { return cNewObjectAction_2_0_0_0; }

		//eClass=[ecore::EClass|QualifiedName]?
		public Assignment getEClassAssignment_2_0_0_1() { return cEClassAssignment_2_0_0_1; }

		//[ecore::EClass|QualifiedName]
		public CrossReference getEClassEClassCrossReference_2_0_0_1_0() { return cEClassEClassCrossReference_2_0_0_1_0; }

		//QualifiedName
		public RuleCall getEClassEClassQualifiedNameParserRuleCall_2_0_0_1_0_1() { return cEClassEClassQualifiedNameParserRuleCall_2_0_0_1_0_1; }

		//name=ValidID?
		public Assignment getNameAssignment_2_0_0_2() { return cNameAssignment_2_0_0_2; }

		//ValidID
		public RuleCall getNameValidIDParserRuleCall_2_0_0_2_0() { return cNameValidIDParserRuleCall_2_0_0_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2_0_0_3() { return cLeftCurlyBracketKeyword_2_0_0_3; }

		//features+=Feature*
		public Assignment getFeaturesAssignment_2_1() { return cFeaturesAssignment_2_1; }

		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_2_1_0() { return cFeaturesFeatureParserRuleCall_2_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2_2() { return cRightCurlyBracketKeyword_2_2; }

		//{Containment.value=current}
		public Action getContainmentValueAction_2_3() { return cContainmentValueAction_2_3; }

		//=> Reference
		public RuleCall getReferenceParserRuleCall_3() { return cReferenceParserRuleCall_3; }
	}

	public class MultiValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.MultiValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMultiValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValuesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValuesValueParserRuleCall_2_0 = (RuleCall)cValuesAssignment_2.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//MultiValue:
		//	{MultiValue} "[" values+=Value* "]";
		@Override public ParserRule getRule() { return rule; }

		//{MultiValue} "[" values+=Value* "]"
		public Group getGroup() { return cGroup; }

		//{MultiValue}
		public Action getMultiValueAction_0() { return cMultiValueAction_0; }

		//"["
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }

		//values+=Value*
		public Assignment getValuesAssignment_2() { return cValuesAssignment_2; }

		//Value
		public RuleCall getValuesValueParserRuleCall_2_0() { return cValuesValueParserRuleCall_2_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_3() { return cRightSquareBracketKeyword_3; }
	}

	public class ReferenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.Reference");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cValueEObjectCrossReference_0 = (CrossReference)cValueAssignment.eContents().get(0);
		private final RuleCall cValueEObjectQualifiedNameParserRuleCall_0_1 = (RuleCall)cValueEObjectCrossReference_0.eContents().get(1);
		
		//Reference:
		//	value=[ecore::EObject|QualifiedName];
		@Override public ParserRule getRule() { return rule; }

		//// NOTE we ref. an EObject, and not an [NewObject].. this EObject is always the
		//// respective "real" EObject, in the derived state if its a reference to something
		//// in an EFactory resource, or a reference to an existing non-EFactory EObject, 
		//// e.g. in an integration scenario with other Xtext grammars.
		//value=[ecore::EObject|QualifiedName]
		public Assignment getValueAssignment() { return cValueAssignment; }

		//[ecore::EObject|QualifiedName]
		public CrossReference getValueEObjectCrossReference_0() { return cValueEObjectCrossReference_0; }

		//QualifiedName
		public RuleCall getValueEObjectQualifiedNameParserRuleCall_0_1() { return cValueEObjectQualifiedNameParserRuleCall_0_1; }
	}

	public class AttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.Attribute");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cEnumAttributeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cStringAttributeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cIntegerAttributeParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cBooleanAttributeParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cDoubleAttributeParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cDateAttributeParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cNullAttributeParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Attribute:
		//	EnumAttribute | StringAttribute | IntegerAttribute | BooleanAttribute | DoubleAttribute | DateAttribute |
		//	NullAttribute;
		@Override public ParserRule getRule() { return rule; }

		//EnumAttribute | StringAttribute | IntegerAttribute | BooleanAttribute | DoubleAttribute | DateAttribute | NullAttribute
		public Alternatives getAlternatives() { return cAlternatives; }

		//EnumAttribute
		public RuleCall getEnumAttributeParserRuleCall_0() { return cEnumAttributeParserRuleCall_0; }

		//StringAttribute
		public RuleCall getStringAttributeParserRuleCall_1() { return cStringAttributeParserRuleCall_1; }

		//IntegerAttribute
		public RuleCall getIntegerAttributeParserRuleCall_2() { return cIntegerAttributeParserRuleCall_2; }

		//BooleanAttribute
		public RuleCall getBooleanAttributeParserRuleCall_3() { return cBooleanAttributeParserRuleCall_3; }

		//DoubleAttribute
		public RuleCall getDoubleAttributeParserRuleCall_4() { return cDoubleAttributeParserRuleCall_4; }

		//DateAttribute
		public RuleCall getDateAttributeParserRuleCall_5() { return cDateAttributeParserRuleCall_5; }

		//NullAttribute
		public RuleCall getNullAttributeParserRuleCall_6() { return cNullAttributeParserRuleCall_6; }
	}

	public class EnumAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.EnumAttribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cColonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cValueEEnumLiteralCrossReference_1_0 = (CrossReference)cValueAssignment_1.eContents().get(0);
		private final RuleCall cValueEEnumLiteralQualifiedNameParserRuleCall_1_0_1 = (RuleCall)cValueEEnumLiteralCrossReference_1_0.eContents().get(1);
		
		//EnumAttribute:
		//	":" value=[ecore::EEnumLiteral|QualifiedName];
		@Override public ParserRule getRule() { return rule; }

		//":" value=[ecore::EEnumLiteral|QualifiedName]
		public Group getGroup() { return cGroup; }

		//":"
		public Keyword getColonKeyword_0() { return cColonKeyword_0; }

		//value=[ecore::EEnumLiteral|QualifiedName]
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//[ecore::EEnumLiteral|QualifiedName]
		public CrossReference getValueEEnumLiteralCrossReference_1_0() { return cValueEEnumLiteralCrossReference_1_0; }

		//QualifiedName
		public RuleCall getValueEEnumLiteralQualifiedNameParserRuleCall_1_0_1() { return cValueEEnumLiteralQualifiedNameParserRuleCall_1_0_1; }
	}

	public class StringAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.StringAttribute");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//// TODO Attribute Types should later not be hard-coded here anymore.. Grammar should be more open & generic.
		//StringAttribute:
		//	value=STRING;
		@Override public ParserRule getRule() { return rule; }

		//value=STRING
		public Assignment getValueAssignment() { return cValueAssignment; }

		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_0() { return cValueSTRINGTerminalRuleCall_0; }
	}

	public class IntegerAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.IntegerAttribute");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueLongParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//IntegerAttribute:
		//	value=Long;
		@Override public ParserRule getRule() { return rule; }

		//value=Long
		public Assignment getValueAssignment() { return cValueAssignment; }

		//Long
		public RuleCall getValueLongParserRuleCall_0() { return cValueLongParserRuleCall_0; }
	}

	public class DoubleAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.DoubleAttribute");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueDoubleParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//DoubleAttribute:
		//	value=Double;
		@Override public ParserRule getRule() { return rule; }

		//value=Double
		public Assignment getValueAssignment() { return cValueAssignment; }

		//Double
		public RuleCall getValueDoubleParserRuleCall_0() { return cValueDoubleParserRuleCall_0; }
	}

	public class DateAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.DateAttribute");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueDateParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//DateAttribute:
		//	value=Date;
		@Override public ParserRule getRule() { return rule; }

		//value=Date
		public Assignment getValueAssignment() { return cValueAssignment; }

		//Date
		public RuleCall getValueDateParserRuleCall_0() { return cValueDateParserRuleCall_0; }
	}

	public class NullAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.NullAttribute");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final Keyword cValueNULLKeyword_0 = (Keyword)cValueAssignment.eContents().get(0);
		
		//NullAttribute:
		//	value="NULL";
		@Override public ParserRule getRule() { return rule; }

		//value="NULL"
		public Assignment getValueAssignment() { return cValueAssignment; }

		//"NULL"
		public Keyword getValueNULLKeyword_0() { return cValueNULLKeyword_0; }
	}

	public class BooleanAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.BooleanAttribute");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueBooleanParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//BooleanAttribute:
		//	value=Boolean;
		@Override public ParserRule getRule() { return rule; }

		//value=Boolean
		public Assignment getValueAssignment() { return cValueAssignment; }

		//Boolean
		public RuleCall getValueBooleanParserRuleCall_0() { return cValueBooleanParserRuleCall_0; }
	}

	public class StringOrQualifiedNameWithWildcardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.StringOrQualifiedNameWithWildcard");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cQualifiedNameWithWildcardParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//StringOrQualifiedNameWithWildcard:
		//	STRING | QualifiedNameWithWildcard;
		@Override public ParserRule getRule() { return rule; }

		//STRING | QualifiedNameWithWildcard
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//QualifiedNameWithWildcard
		public RuleCall getQualifiedNameWithWildcardParserRuleCall_1() { return cQualifiedNameWithWildcardParserRuleCall_1; }
	}

	public class QualifiedNameWithWildcardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.QualifiedNameWithWildcard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cQualifiedNameParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopAsteriskKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//QualifiedNameWithWildcard:
		//	QualifiedName '.*'?;
		@Override public ParserRule getRule() { return rule; }

		//QualifiedName '.*'?
		public Group getGroup() { return cGroup; }

		//QualifiedName
		public RuleCall getQualifiedNameParserRuleCall_0() { return cQualifiedNameParserRuleCall_0; }

		//'.*'?
		public Keyword getFullStopAsteriskKeyword_1() { return cFullStopAsteriskKeyword_1; }
	}

	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cValidIDParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cValidIDParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ValidID (=> '.' ValidID)*;
		@Override public ParserRule getRule() { return rule; }

		//ValidID (=> '.' ValidID)*
		public Group getGroup() { return cGroup; }

		//ValidID
		public RuleCall getValidIDParserRuleCall_0() { return cValidIDParserRuleCall_0; }

		//(=> '.' ValidID)*
		public Group getGroup_1() { return cGroup_1; }

		//=> '.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ValidID
		public RuleCall getValidIDParserRuleCall_1_1() { return cValidIDParserRuleCall_1_1; }
	}

	public class ValidIDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.ValidID");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cLONG_IDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cLONG_UNSIGNEDTerminalRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//ValidID:
		//	ID | LONG_ID | LONG_UNSIGNED;
		@Override public ParserRule getRule() { return rule; }

		//ID | LONG_ID | LONG_UNSIGNED
		public Alternatives getAlternatives() { return cAlternatives; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//LONG_ID
		public RuleCall getLONG_IDTerminalRuleCall_1() { return cLONG_IDTerminalRuleCall_1; }

		//LONG_UNSIGNED
		public RuleCall getLONG_UNSIGNEDTerminalRuleCall_2() { return cLONG_UNSIGNEDTerminalRuleCall_2; }
	}

	public class BooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.Boolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//// This is needed so that IDs consisting only of digit/numbers work, including in QualifiedName (DS-8268).
		//// Double and Date are Xtext data types instead of terminals, because if they are terminals there is some confusion about the '.' in them vs. the QualifiedName dot in case a QualifiedName has parts consisting only of numbers  
		//Boolean ecore::EBoolean:
		//	"true" | "false";
		@Override public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}

	public class LongElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.Long");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cLONG_UNSIGNEDTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//Long ecore::ELong:
		//	'-'? LONG_UNSIGNED;
		@Override public ParserRule getRule() { return rule; }

		//'-'? LONG_UNSIGNED
		public Group getGroup() { return cGroup; }

		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//LONG_UNSIGNED
		public RuleCall getLONG_UNSIGNEDTerminalRuleCall_1() { return cLONG_UNSIGNEDTerminalRuleCall_1; }
	}

	public class DoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.Double");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cLongParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cLONG_UNSIGNEDTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//Double ecore::EDouble:
		//	Long '.' LONG_UNSIGNED;
		@Override public ParserRule getRule() { return rule; }

		//Long '.' LONG_UNSIGNED
		public Group getGroup() { return cGroup; }

		//Long
		public RuleCall getLongParserRuleCall_0() { return cLongParserRuleCall_0; }

		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }

		//LONG_UNSIGNED
		public RuleCall getLONG_UNSIGNEDTerminalRuleCall_2() { return cLONG_UNSIGNEDTerminalRuleCall_2; }
	}

	public class DateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.Date");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cLONG_UNSIGNEDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cLONG_UNSIGNEDTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Keyword cFullStopKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final RuleCall cLONG_UNSIGNEDTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//Date ecore::EDate:
		//	LONG_UNSIGNED '.' LONG_UNSIGNED '.' LONG_UNSIGNED;
		@Override public ParserRule getRule() { return rule; }

		//LONG_UNSIGNED '.' LONG_UNSIGNED '.' LONG_UNSIGNED
		public Group getGroup() { return cGroup; }

		//LONG_UNSIGNED
		public RuleCall getLONG_UNSIGNEDTerminalRuleCall_0() { return cLONG_UNSIGNEDTerminalRuleCall_0; }

		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }

		//LONG_UNSIGNED
		public RuleCall getLONG_UNSIGNEDTerminalRuleCall_2() { return cLONG_UNSIGNEDTerminalRuleCall_2; }

		//'.'
		public Keyword getFullStopKeyword_3() { return cFullStopKeyword_3; }

		//LONG_UNSIGNED
		public RuleCall getLONG_UNSIGNEDTerminalRuleCall_4() { return cLONG_UNSIGNEDTerminalRuleCall_4; }
	}
	
	
	private final FactoryElements pFactory;
	private final PackageImportElements pPackageImport;
	private final NamespaceImportElements pNamespaceImport;
	private final AnnotationElements pAnnotation;
	private final CustomNameMappingElements pCustomNameMapping;
	private final FeatureElements pFeature;
	private final NewObjectElements pNewObject;
	private final ValueElements pValue;
	private final MultiValueElements pMultiValue;
	private final ReferenceElements pReference;
	private final AttributeElements pAttribute;
	private final EnumAttributeElements pEnumAttribute;
	private final StringAttributeElements pStringAttribute;
	private final IntegerAttributeElements pIntegerAttribute;
	private final DoubleAttributeElements pDoubleAttribute;
	private final DateAttributeElements pDateAttribute;
	private final NullAttributeElements pNullAttribute;
	private final BooleanAttributeElements pBooleanAttribute;
	private final StringOrQualifiedNameWithWildcardElements pStringOrQualifiedNameWithWildcard;
	private final QualifiedNameWithWildcardElements pQualifiedNameWithWildcard;
	private final QualifiedNameElements pQualifiedName;
	private final ValidIDElements pValidID;
	private final BooleanElements pBoolean;
	private final LongElements pLong;
	private final DoubleElements pDouble;
	private final DateElements pDate;
	private final TerminalRule tLONG_ID;
	private final TerminalRule tLONG_UNSIGNED;
	private final TerminalRule tID;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public EFactoryGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pFactory = new FactoryElements();
		this.pPackageImport = new PackageImportElements();
		this.pNamespaceImport = new NamespaceImportElements();
		this.pAnnotation = new AnnotationElements();
		this.pCustomNameMapping = new CustomNameMappingElements();
		this.pFeature = new FeatureElements();
		this.pNewObject = new NewObjectElements();
		this.pValue = new ValueElements();
		this.pMultiValue = new MultiValueElements();
		this.pReference = new ReferenceElements();
		this.pAttribute = new AttributeElements();
		this.pEnumAttribute = new EnumAttributeElements();
		this.pStringAttribute = new StringAttributeElements();
		this.pIntegerAttribute = new IntegerAttributeElements();
		this.pDoubleAttribute = new DoubleAttributeElements();
		this.pDateAttribute = new DateAttributeElements();
		this.pNullAttribute = new NullAttributeElements();
		this.pBooleanAttribute = new BooleanAttributeElements();
		this.pStringOrQualifiedNameWithWildcard = new StringOrQualifiedNameWithWildcardElements();
		this.pQualifiedNameWithWildcard = new QualifiedNameWithWildcardElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pValidID = new ValidIDElements();
		this.pBoolean = new BooleanElements();
		this.pLong = new LongElements();
		this.pDouble = new DoubleElements();
		this.pDate = new DateElements();
		this.tLONG_ID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.LONG_ID");
		this.tLONG_UNSIGNED = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.LONG_UNSIGNED");
		this.tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.eclipse.emf.eson.EFactory.ID");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.eclipse.emf.eson.EFactory".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Factory:
	//	imports+=NamespaceImport*
	//	ePackages+=PackageImport*
	//	annotations+=Annotation*
	//	root=NewObject;
	public FactoryElements getFactoryAccess() {
		return pFactory;
	}
	
	public ParserRule getFactoryRule() {
		return getFactoryAccess().getRule();
	}

	//PackageImport:
	//	'use' ePackage=[ecore::EPackage|StringOrQualifiedNameWithWildcard];
	public PackageImportElements getPackageImportAccess() {
		return pPackageImport;
	}
	
	public ParserRule getPackageImportRule() {
		return getPackageImportAccess().getRule();
	}

	//NamespaceImport:
	//	'import' importedNamespace=QualifiedNameWithWildcard
	//	// TODO Content Assist for EPackage .. but one COULD also import other named NewObject / EObject, instead of EPackages.. hm. As EPackage will be much more common, just support that.	
	//;
	public NamespaceImportElements getNamespaceImportAccess() {
		return pNamespaceImport;
	}
	
	public ParserRule getNamespaceImportRule() {
		return getNamespaceImportAccess().getRule();
	}

	//Annotation:
	//	CustomNameMapping;
	public AnnotationElements getAnnotationAccess() {
		return pAnnotation;
	}
	
	public ParserRule getAnnotationRule() {
		return getAnnotationAccess().getRule();
	}

	//// TODO further consider if name mapping is best put in-line into objects.. it would have to repeat in every file..
	//// logically this rather belongs into an external mapping, like HUTN's Configuration (HutnConfig), or even better directly into an Xcore as annotations 
	//CustomNameMapping:
	//	"@Name" "{" eClass=[ecore::EClass|QualifiedName] "=" nameFeature=[ecore::EAttribute|QualifiedName] "}";
	public CustomNameMappingElements getCustomNameMappingAccess() {
		return pCustomNameMapping;
	}
	
	public ParserRule getCustomNameMappingRule() {
		return getCustomNameMappingAccess().getRule();
	}

	//Feature:
	//	eFeature=[ecore::EStructuralFeature|QualifiedName] ":" value=Value?;
	public FeatureElements getFeatureAccess() {
		return pFeature;
	}
	
	public ParserRule getFeatureRule() {
		return getFeatureAccess().getRule();
	}

	//// Re. use of QualifiedName, see SimplestWeiredNameTest (we want to permit EAttribute name to have dots; strange yes, but due to a particular requirement in an in-house closed source product)
	//// Also value isn't really optional semantically of course
	//// but because it may be missing while typing, this works out much better in practice like this
	//// the EFactoryJavaValidator flags it up if it's really missing
	//// without this, there are confusing parsing errors, the proposal provider doesn't work as it should, etc.
	//NewObject:
	//	eClass=[ecore::EClass|QualifiedName] name=ValidID? "{"
	//	features+=Feature*
	//	"}";
	public NewObjectElements getNewObjectAccess() {
		return pNewObject;
	}
	
	public ParserRule getNewObjectRule() {
		return getNewObjectAccess().getRule();
	}

	//Value:
	//	MultiValue
	//	| Attribute | // Following is an in-lined NewObject, if making changes, adapt above too
	//	=> ({NewObject} eClass=[ecore::EClass|QualifiedName]? name=ValidID? "{") features+=Feature*
	//	"}" {Containment.value=current} | => Reference;
	public ValueElements getValueAccess() {
		return pValue;
	}
	
	public ParserRule getValueRule() {
		return getValueAccess().getRule();
	}

	//MultiValue:
	//	{MultiValue} "[" values+=Value* "]";
	public MultiValueElements getMultiValueAccess() {
		return pMultiValue;
	}
	
	public ParserRule getMultiValueRule() {
		return getMultiValueAccess().getRule();
	}

	//Reference:
	//	value=[ecore::EObject|QualifiedName];
	public ReferenceElements getReferenceAccess() {
		return pReference;
	}
	
	public ParserRule getReferenceRule() {
		return getReferenceAccess().getRule();
	}

	//Attribute:
	//	EnumAttribute | StringAttribute | IntegerAttribute | BooleanAttribute | DoubleAttribute | DateAttribute |
	//	NullAttribute;
	public AttributeElements getAttributeAccess() {
		return pAttribute;
	}
	
	public ParserRule getAttributeRule() {
		return getAttributeAccess().getRule();
	}

	//EnumAttribute:
	//	":" value=[ecore::EEnumLiteral|QualifiedName];
	public EnumAttributeElements getEnumAttributeAccess() {
		return pEnumAttribute;
	}
	
	public ParserRule getEnumAttributeRule() {
		return getEnumAttributeAccess().getRule();
	}

	//// TODO Attribute Types should later not be hard-coded here anymore.. Grammar should be more open & generic.
	//StringAttribute:
	//	value=STRING;
	public StringAttributeElements getStringAttributeAccess() {
		return pStringAttribute;
	}
	
	public ParserRule getStringAttributeRule() {
		return getStringAttributeAccess().getRule();
	}

	//IntegerAttribute:
	//	value=Long;
	public IntegerAttributeElements getIntegerAttributeAccess() {
		return pIntegerAttribute;
	}
	
	public ParserRule getIntegerAttributeRule() {
		return getIntegerAttributeAccess().getRule();
	}

	//DoubleAttribute:
	//	value=Double;
	public DoubleAttributeElements getDoubleAttributeAccess() {
		return pDoubleAttribute;
	}
	
	public ParserRule getDoubleAttributeRule() {
		return getDoubleAttributeAccess().getRule();
	}

	//DateAttribute:
	//	value=Date;
	public DateAttributeElements getDateAttributeAccess() {
		return pDateAttribute;
	}
	
	public ParserRule getDateAttributeRule() {
		return getDateAttributeAccess().getRule();
	}

	//NullAttribute:
	//	value="NULL";
	public NullAttributeElements getNullAttributeAccess() {
		return pNullAttribute;
	}
	
	public ParserRule getNullAttributeRule() {
		return getNullAttributeAccess().getRule();
	}

	//BooleanAttribute:
	//	value=Boolean;
	public BooleanAttributeElements getBooleanAttributeAccess() {
		return pBooleanAttribute;
	}
	
	public ParserRule getBooleanAttributeRule() {
		return getBooleanAttributeAccess().getRule();
	}

	//StringOrQualifiedNameWithWildcard:
	//	STRING | QualifiedNameWithWildcard;
	public StringOrQualifiedNameWithWildcardElements getStringOrQualifiedNameWithWildcardAccess() {
		return pStringOrQualifiedNameWithWildcard;
	}
	
	public ParserRule getStringOrQualifiedNameWithWildcardRule() {
		return getStringOrQualifiedNameWithWildcardAccess().getRule();
	}

	//QualifiedNameWithWildcard:
	//	QualifiedName '.*'?;
	public QualifiedNameWithWildcardElements getQualifiedNameWithWildcardAccess() {
		return pQualifiedNameWithWildcard;
	}
	
	public ParserRule getQualifiedNameWithWildcardRule() {
		return getQualifiedNameWithWildcardAccess().getRule();
	}

	//QualifiedName:
	//	ValidID (=> '.' ValidID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//ValidID:
	//	ID | LONG_ID | LONG_UNSIGNED;
	public ValidIDElements getValidIDAccess() {
		return pValidID;
	}
	
	public ParserRule getValidIDRule() {
		return getValidIDAccess().getRule();
	}

	//// This is needed so that IDs consisting only of digit/numbers work, including in QualifiedName (DS-8268).
	//// Double and Date are Xtext data types instead of terminals, because if they are terminals there is some confusion about the '.' in them vs. the QualifiedName dot in case a QualifiedName has parts consisting only of numbers  
	//Boolean ecore::EBoolean:
	//	"true" | "false";
	public BooleanElements getBooleanAccess() {
		return pBoolean;
	}
	
	public ParserRule getBooleanRule() {
		return getBooleanAccess().getRule();
	}

	//Long ecore::ELong:
	//	'-'? LONG_UNSIGNED;
	public LongElements getLongAccess() {
		return pLong;
	}
	
	public ParserRule getLongRule() {
		return getLongAccess().getRule();
	}

	//Double ecore::EDouble:
	//	Long '.' LONG_UNSIGNED;
	public DoubleElements getDoubleAccess() {
		return pDouble;
	}
	
	public ParserRule getDoubleRule() {
		return getDoubleAccess().getRule();
	}

	//Date ecore::EDate:
	//	LONG_UNSIGNED '.' LONG_UNSIGNED '.' LONG_UNSIGNED;
	public DateElements getDateAccess() {
		return pDate;
	}
	
	public ParserRule getDateRule() {
		return getDateAccess().getRule();
	}

	//terminal LONG_ID:
	//	LONG_UNSIGNED ID;
	public TerminalRule getLONG_IDRule() {
		return tLONG_ID;
	} 

	//terminal LONG_UNSIGNED returns ecore::ELong:
	//	'0'..'9'+;
	public TerminalRule getLONG_UNSIGNEDRule() {
		return tLONG_UNSIGNED;
	} 

	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_' | ',' | '-') ('a'..'z' | 'A'..'Z' | '_' | ',' | '-' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return tID;
	} 

	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
