<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="lineage" nsURI="http://www.eclipse.org/efbt/lineage" nsPrefix="lineage">
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Scenario"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Scenario"/>
      <details key="kind" value="empty"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name of the Scenario"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="name"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invisible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name of the Scenario"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="description"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredAttributes" upperBound="-1"
        eType="ecore:EClass Xcore.ecore#//XMember"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data_constraints" eType="#//DataConstraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attr1" eType="ecore:EClass Xcore.ecore#//XAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparison" eType="#//AttrComparison"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" eType="ecore:EClass Xcore.ecore#//XAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AttrComparison">
    <eLiterals name="equals"/>
    <eLiterals name="less_than" value="1"/>
    <eLiterals name="greater_than" value="2"/>
    <eLiterals name="not_equals" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScenarioTag" eSuperTypes="requirements_text.ecore#//Tag">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Tag which tags a Scenario in order to link it with requirements."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenario" eType="#//Scenario">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The tagged Scenario."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationLineage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="ecore:EClass Xcore.ecore#//XOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
        eType="#//Scenario" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredAttributesForScenarioChoice"
        upperBound="-1" eType="ecore:EClass Xcore.ecore#//XMember"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineageModel" eSuperTypes="module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationsLineage" upperBound="-1"
        eType="#//OperationLineage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioTags" upperBound="-1"
        eType="#//ScenarioTag" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
