<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sql_lite" nsURI="http://www.example.org/sql_lite" nsPrefix="sql_lite">
  <eClassifiers xsi:type="ecore:EClass" name="View" eSuperTypes="#//SQLEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectClause" eType="#//SelectClause"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromClause" eType="#//FromClause"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whereClause" eType="#//WhereClause"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//SelectColumn" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="as" eType="ecore:EClass data_meta_model.ecore#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectColumnMemberAs" eSuperTypes="#//SelectColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberAsConstant" eType="ecore:EClass data_meta_model.ecore#//EnumMember"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectColumnAttributeAs" eSuperTypes="#//SelectColumn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="ecore:EClass data_meta_model.ecore#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhereClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute1" eType="ecore:EClass data_meta_model.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparitor" eType="#//Comparitor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" eType="ecore:EClass data_meta_model.ecore#//EnumMember"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SQLEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FromClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sqlEntities" eType="#//SQLEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SQLEntityModule" eSuperTypes="module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sqlEntities" upperBound="-1"
        eType="#//SQLEntity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratedEntitySQL">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generatedEntity" eType="ecore:EClass data_meta_model.ecore#//GeneratedEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="view" upperBound="-1" eType="#//View"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratedEntitySQLModule" eSuperTypes="module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="GeneratedEntitySQLs" upperBound="-1"
        eType="#//GeneratedEntitySQL" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Comparitor">
    <eLiterals name="less_than"/>
    <eLiterals name="equals"/>
    <eLiterals name="greater_than"/>
  </eClassifiers>
</ecore:EPackage>
