<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vtl_logic" nsURI="http://www.eclipse.org/efbt/vtl_logic" nsPrefix="vtl_logic">
  <eClassifiers xsi:type="ecore:EClass" name="VTLGeneratedOutputlayer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependant_intermediate_layers"
        upperBound="-1" eType="#//VTLGeneratedIntermediateLayer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VTLForOutputLayerAndIntemedateLayerCombinations"
        upperBound="-1" eType="#//VTLForOutputLayerAndIntermediateLayerCombination"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputLayer" eType="ecore:EClass Xcore.ecore#//XClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTLForOutputLayerAndIntermediateLayerCombination">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformations" upperBound="-1"
        eType="#//VTLTransformation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputLayer" eType="#//VTLGeneratedOutputlayer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intermediateLayer" eType="#//VTLGeneratedIntermediateLayer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTLGeneratedIntermediateLayer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependant_enriched_cubes"
        eType="#//VTLGeneratedIntermediateLayer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformations" upperBound="-1"
        eType="#//VTLTransformation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEnrichment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTLTransformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transformation_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order_in_scheme" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTLScheme">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//VTLTransformation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scheme_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTLForSelectionLayer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectionLayer" eType="ecore:EClass sql_lite.ecore#//LayerSQL"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputLayer" eType="#//VTLGeneratedOutputlayer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intermediateLayer" eType="#//VTLGeneratedIntermediateLayer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTLModule" eSuperTypes="module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="VTLSchemes" eType="#//VTLSchemesModule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VTLGeneratedOutputLayers"
        eType="#//VTLGeneratedOutputlayerModule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VTLGeneratedIntermediateLayers"
        eType="#//VTLGeneratedIntermediateLayerModule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VTLEnrichedLayers" eType="#//VTLGeneratedIntermediateLayerModule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VTLForSelectionLayers"
        eType="#//VTLForSelectionLayerModule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityToVTLIntermediateLayerLinks"
        eType="#//EntityToVTLIntermediateLayerLinkModule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VTLForViews" eType="#//VTLForViewModule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityToVTLIntermediateLayerLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="VTLIntermediateLayer" eType="#//VTLGeneratedIntermediateLayer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="ecore:EClass Xcore.ecore#//XClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTLForView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="view" eType="ecore:EClass sql_lite.ecore#//View"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vtl" eType="#//VTLGeneratedOutputlayer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTLGeneratedOutputlayerModule" eSuperTypes="module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vTLGeneratedOutputlayerModules"
        upperBound="-1" eType="#//VTLGeneratedOutputlayer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTLForOutputLayerAndIntermediateLayerCombinationModule"
      eSuperTypes="module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vTLForOutputLayerAndIntermediateLayerCombinations"
        upperBound="-1" eType="#//VTLForOutputLayerAndIntermediateLayerCombinationModule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTLGeneratedIntermediateLayerModule"
      eSuperTypes="module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vTLGeneratedIntermediateLayers"
        upperBound="-1" eType="#//VTLGeneratedIntermediateLayer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTLSchemesModule" eSuperTypes="module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vTLSchemes" upperBound="-1"
        eType="#//VTLScheme" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTLForSelectionLayerModule" eSuperTypes="module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vTLForSelectionLayers"
        upperBound="-1" eType="#//VTLForSelectionLayer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityToVTLIntermediateLayerLinkModule"
      eSuperTypes="module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityToVTLIntermediateLayerLinks"
        upperBound="-1" eType="#//EntityToVTLIntermediateLayerLink" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VTLForViewModule" eSuperTypes="module_management.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vTLForViews" upperBound="-1"
        eType="#//VTLForView" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
