<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="output_data_structures" nsURI="http://www.eclipse.org/output_data_structures"
    nsPrefix="output_data_structures">
  <eClassifiers xsi:type="ecore:EClass" name="OutputDataStructureModule" eSuperTypes="../../org.eclipse.efbt.oa4rtt.model.module_management/model/module_management.ecore#//Module"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputDataStructure"/>
</ecore:EPackage>
