/*
 * generated by Xtext 2.21.0
 */
package org.eclipse.efbt.aorta.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractAortaValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/aorta_program"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/test_definition"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/functionality_module"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/requirements_text"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/test_input_data"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/test"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/base_column_structured_data"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/column_structures"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/report_structures"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/requirements_artefacts"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/module_management"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/emf/2002/Ecore"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/execution_environments"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/column_structured_data"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/input_data_structures"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/output_data_structures"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/scenarios"));
		return result;
	}
}
