<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test_definition" nsURI="http://www.eclipse.org/efbt/test_definition"
    nsPrefix="test_definition">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="This package describes how we describe tests and groups of tests.&#xA;Test Definitions are defined using given , when , and then  clauses as used in the popular Gherkin language for defining tests according to the Behaviour Driven Developement (BDD) approach.&#xA;We can have multiple tests with different test data which are linked to the same test definition.&#xA;In order to group tests together, we parameterize the clauses of test definitions, this is also popular in BDD.&#xA;In order to provide well defined coverage, we constrain how the parameters can be set to a particular set of values, the way we constrain this is by defineing in constraints what the 'parent object' of a parameter is. &#xA;By having a contrained list of choices for a parameter, we can create a coverage grid of the set of possible combined  choices for the parameters of a test definition.&#xA;"/>
  </eAnnotations>
  <eAnnotations source="license">
    <details key="license" value="Copyright (c) 2019 Bird Software Solutions Ltd&#xA; All rights reserved. This file and the accompanying materials are made available under the terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at http://www.eclipse.org/legal/epl-v20.html&#xA;&#xA;SPDX-License-Identifier: EPL-2.0 &#xA;&#xA; Contributors:&#xA; Neil Mackenzie - initial API and implementation&#xD;"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="BDDTestContraints">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="a set of  contraints upon the parameters described in an associated Test Template"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="template" eType="#//BDDTestTemplate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The associated Test Template"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name, and unique ID, of the constraints"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="givenParams" upperBound="-1"
        eType="#//Param" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A set of constraints for the parameterization of the individual parameters of the given clause of a test template. &#xA;In a test definition which refers to this constraint, then for each parameter, only child elements of the objects chosen in this constraints information can be selected.&#xA;This constrant is technically  enforce using scoping rules. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whenParams" upperBound="-1"
        eType="#//Param" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A set of constraints for the parameterization of the individual parameters of the when clause of a test template. &#xA;In a test definition which refers to this constraint, then for each parameter, only child elements of the objects chosen in this constraints information can be selected.&#xA;This constrant is technically  enforce using scoping rules. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenParams" upperBound="-1"
        eType="#//Param" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A set of constraints for the parameterization of the individual parameters of the then clause of a test template. &#xA;In a test definition which refers to this constraint, then for each parameter, only child elements of the objects chosen in this constraints information can be selected.&#xA;This constrant is technically  enforce using scoping rules. "/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BDDTestTemplateModule" eSuperTypes="../../org.eclipse.efbt.cocalimo.core.model.module_management/model/module_management.ecore#//Module">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Module with a set of TestTemplates"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="templates" upperBound="-1"
        eType="#//BDDTestTemplate" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The templates"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BDDTestTemplate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A TestTemplates describes what parameters exist in the given when and then clauses of a TestDefinition. &#xA;It also gives and example of one valid setting for each Parameter, this is an easy way to set the type of the parameter by example.&#xA;The actual parameters of the TestDefintion should be set to objects of the same type as the example parmater, and should meet the contraints defined int he TestConstraints associated with the TestDefinition."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name, and id, of the TestTemplate"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="givenText" eType="#//ClauseText"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The text of the given clause"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whenText" eType="#//ClauseText"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The text of the when  clause"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenText" eType="#//ClauseText"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The text of the then clause"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="givenParams" upperBound="-1"
        eType="#//Param" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The parameters of the given clause"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="whenParams" upperBound="-1"
        eType="#//Param" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The parameters of the when clause"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenParams" upperBound="-1"
        eType="#//Param" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The parameters of the then clause"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BDDTestConstraintsModule" eSuperTypes="../../org.eclipse.efbt.cocalimo.core.model.module_management/model/module_management.ecore#//Module">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A module containing a set of TestContraints"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverageTestSets" upperBound="-1"
        eType="#//BDDTestContraints" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The TestConstraints"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BDDTestDefinition" eSuperTypes="#//TestDefinition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A TestDefinition decribes a parameterised test. It references a TestConstraint that it meets, which in turn references a TestTemplate that it meets to define the parameters that must be set and their expected types provided by example."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testContraints" eType="#//BDDTestContraints">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The constraints met by the TestDefinition"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="given" eType="#//Given"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The given clause of the test"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="when" eType="#//When" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The when clause of the test"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#//Then" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The then clause of the test"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="E2EBDDTestDefinition" eSuperTypes="#//BDDTestDefinition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A TestDefinition which represents and End To End Test"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitTestDefinition" eSuperTypes="#//BDDTestDefinition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A TestDefinition which represents a Unit  Test"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A cluase, i.e a given when or then clause."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//ClauseText">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The text of a clause"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//Param" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The parameters of a clause"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regulatoryTextLinks" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.efbt.cocalimo.core.model.requirements_text/model/requirements_text.ecore#//TitledRequirementsSection">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The links to regulatory text for a clause"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Param">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Parameter of a clause, these should be set in the test definition"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The object to which the parameter is set."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Given" eSuperTypes="#//Clause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Given clause"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="When" eSuperTypes="#//Clause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A When clause"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Then" eSuperTypes="#//Clause">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Then clause"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClauseText">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The text of a clause"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The text of a clause, for now this should have no spaces making it a valid ID."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoverageGrid">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="For a TestConstraint, we can imagine the complete set of combinations of  possible parameters that meet the constraint, make up a coverage grid."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverageTestSet" eType="#//BDDTestContraints">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Test Constraint"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coverageGridPoints" eType="#//CoverageGridPoint"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="One Point of the Coverage grid"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name of the coverage grid"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoverageGridPoint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="One Point of the Coverage grid"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The set of parameter values that identify that grid point."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BDDTestDefinitionModule" eSuperTypes="../../org.eclipse.efbt.cocalimo.core.model.module_management/model/module_management.ecore#//Module">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A module containing a set of TestDefinitions"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testDefinitions" upperBound="-1"
        eType="#//BDDTestDefinition" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The TestDefinitions"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestDefinition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A TestDefinition decribes a parameterised test. It references a TestConstraint that it meets, which in turn references a TestTemplate that it meets to define the parameters that must be set and their expected types provided by example."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name of the TestDefinition"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegFunctionalityTestDefinition" eSuperTypes="#//TestDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputModules" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.efbt.cocalimo.core.model.functionality_module/model/functionality_module.ecore#//ReadDataSourceFunctionalityModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processingModules" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.efbt.cocalimo.core.model.functionality_module/model/functionality_module.ecore#//FunctionalityModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reportCellCreationModules"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.efbt.cocalimo.core.model.functionality_module/model/functionality_module.ecore#//ReportCellCreationFunctionalityModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.efbt.cocalimo.core.model.functionality_module/model/scenarios.ecore#//Scenario"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegFunctionalityTestDefinitionModule"
      eSuperTypes="../../org.eclipse.efbt.cocalimo.core.model.module_management/model/module_management.ecore#//Module">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A module containing a set of TestDefinitions"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testDefinitions" upperBound="-1"
        eType="#//RegFunctionalityTestDefinition" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The TestDefinitions"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
