/*
 * generated by Xtext 2.26.0
 */
package org.eclipse.efbt.openregspecs.ide;


/**
 * Use this class to register ide components.
 */
public class OpenRegSpecsDSLIdeModule extends AbstractOpenRegSpecsDSLIdeModule {
}
