<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="open_reg_specs" nsURI="http://www.eclipse.org/efbt/open_reg_specs"
    nsPrefix="open_reg_specs">
  <eClassifiers xsi:type="ecore:EClass" name="OpenRegSpecs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="ecore:EClass ../core_model/requirements_text.ecore#//RequirementsModule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types_and_concepts" eType="ecore:EClass openregspecs_smcubes_core_extension.ecore#//SMCubesCoreModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data_model" upperBound="-1"
        eType="ecore:EClass ../core_model/data_meta_model.ecore#//EntityModule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="process_workflow" upperBound="-1"
        eType="ecore:EClass ../core_model/bpmn_lite.ecore#//WorkflowModule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="report_generation" upperBound="-1"
        eType="ecore:EClass ../core_model/sql_lite.ecore#//SQLEntityModule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tests" upperBound="-1"
        eType="ecore:EClass ../core_model/testing.ecore#//TestModule" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
