<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="navigation_context" nsURI="http://www.eclipse.org/navigation_context"
    nsPrefix="navigation_context">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value=" This package describes NavigationContext, used to tie together a set of artifacts with tags and requiremnts "/>
  </eAnnotations>
  <eAnnotations source="license">
    <details key="license" value="Copyright (c) 2019 Openregtech Ltd&#xA; All rights reserved. This file and the accompanying materials are made available under the terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at http://www.eclipse.org/legal/epl-v20.html&#xA;&#xA;SPDX-License-Identifier: EPL-2.0 &#xA;&#xA; Contributors:&#xA; Neil Mackenzie - initial API and implementation&#xD;"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationContext">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value=" The NavigationContextis used to tie together a set of artifacts with tags and requirements.&#xA;    Note that it is possible to have more than one set of tags which link different requirments to the same artefacts.&#xA;    We see this in regulatory reporting when different national regulations might want to use the same logic.&#xA;    The navigation context makes it clear which links we want to use when navigating related links."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="NavigationContext"/>
      <details key="kind" value="empty"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" eType="ecore:EClass ../../org.eclipse.efbt.chirp/model/requirements_text.ecore#//TagGroup">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The related set of tags"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="tags"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformationContext"
        eType="ecore:EClass ../../org.eclipse.efbt.trl.model.trl/model/transformation.ecore#//VersionedComponentsSet">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The related transformation context"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="transformationContext"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformationsSchemeModule"
        eType="ecore:EClass ../../org.eclipse.efbt.chirp/model/functionality_module.ecore#//FunctionalityModuleModule">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The related Transformation Module"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="transformationsSchemeModule"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="license" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="birdModel" eType="ecore:EClass ../../org.eclipse.efbt.bird.model/model/bird_model.ecore#//BIRDModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainModelMapping" eType="ecore:EClass ../../org.eclipse.efbt.trl.model.trl/model/domain_model_mapping.ecore#//DomainMappingModule"/>
  </eClassifiers>
</ecore:EPackage>
