<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="efbt_mapping" nsURI="http://www.eclipse.org/efbt_mapping" nsPrefix="efbt_mapping">
  <eAnnotations source="license">
    <details key="license" value="Copyright (c) 2020 Bird Software Solutions Ltd&#xA; All rights reserved. This file and the accompanying materials are made available under the terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at http://www.eclipse.org/legal/epl-v20.html&#xA;&#xA;SPDX-License-Identifier: EPL-2.0 &#xA;&#xA; Contributors:&#xA; Neil Mackenzie - initial API and implementation&#xD;"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="This Package contains the Modules comtaining SMCubes Mappings"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="MappingDefinitionModule" eSuperTypes="../module_management/module_management.ecore#//Module">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Module containing SMCubes MappingDefintitions"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="ecore:EClass mapping.ecore#//MAPPING_DEFINITION" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The  MappingDefintitions"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CubeMappingModule" eSuperTypes="../module_management/module_management.ecore#//Module">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Module containing SMCubes CubeMappings"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cubeMappings" upperBound="-1"
        eType="ecore:EClass mapping.ecore#//CUBE_MAPPING" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The CubeMappings"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemberMappingModule" eSuperTypes="../module_management/module_management.ecore#//Module">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Module containing SMCubes MemberMappings"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberMappings" upperBound="-1"
        eType="ecore:EClass mapping.ecore#//MEMBER_MAPPING" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The MemberMappings"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableMappingModule" eSuperTypes="../module_management/module_management.ecore#//Module">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A Module containing SMCubes VariableMappings"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableMappings" upperBound="-1"
        eType="ecore:EClass mapping.ecore#//VARIABLE_MAPPING" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The  VariableMappings"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
