/*
 * generated by Xtext 2.23.0
 */
package org.eclipse.emf.eson.ide;


/**
 * Use this class to register ide components.
 */
public class EFactoryIdeModule extends AbstractEFactoryIdeModule {
}
