/*
 * generated by Xtext 2.21.0
 */
package org.eclipse.efbt.aorta.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.efbt.aorta.parser.antlr.internal.InternalAortaParser;
import org.eclipse.efbt.aorta.services.AortaGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class AortaParser extends AbstractAntlrParser {

	@Inject
	private AortaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAortaParser createParser(XtextTokenStream stream) {
		return new InternalAortaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public AortaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AortaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
