/*
 * generated by Xtext 2.21.0
 */
package org.eclipse.efbt.aorta.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AortaAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/eclipse/efbt/aorta/parser/antlr/internal/InternalAorta.tokens");
	}
}
