<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="report_structures" nsURI="http://www.eclipse.org/report_structures"
    nsPrefix="report_structures">
  <eClassifiers xsi:type="ecore:EClass" name="RegReportCell" eSuperTypes="output_data_structures.ecore#//OutputDataStructure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegReportCellValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cell" eType="#//RegReportCell"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegReport">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" upperBound="-1"
        eType="#//RegReportCell" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//RegReportRow"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
        eType="#//RegReportColumn" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegReportModule" eSuperTypes="output_data_structures.ecore#//OutputDataStructureModule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reportGroups" upperBound="-1"
        eType="#//ReportGroup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="regReports" upperBound="-1"
        eType="#//RegReport" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegReportColumn">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegReportRow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReportLinkedRequirement" eSuperTypes="../../org.eclipse.efbt.requirements.core.model.requirements_text/model/requirements_text.ecore#//RequirementsSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="row" eType="#//RegReportRow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" eType="#//RegReportColumn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cell" eType="#//RegReportCell"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
