<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="technical_specification_breakdown" nsURI="http://www.eclipse.org/technical_specification_breakdown"
    nsPrefix="technical_specification_breakdown">
  <eClassifiers xsi:type="ecore:EClass" name="TechnicalSpecificationFunctionalityModuleModule"
      eSuperTypes="functionality_module.ecore#//FunctionalityModuleModule"/>
</ecore:EPackage>
