/*
 * generated by Xtext 2.26.0
 */
package org.eclipse.efbt.openregspecs.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class OpenRegSpecsStandaloneSetup extends OpenRegSpecsStandaloneSetupGenerated {

	public static void doSetup() {
		new OpenRegSpecsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
