<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mapping" nsURI="http://www.eclipse.org/efbt/mapping" nsPrefix="mapping">
  <eAnnotations source="license">
    <details key="license" value="Copyright (c) 2020 Bird Software Solutions Ltd&#xA; All rights reserved. This file and the accompanying materials are made available under the terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at http://www.eclipse.org/legal/epl-v20.html&#xA;&#xA;SPDX-License-Identifier: EPL-2.0 &#xA;&#xA; Contributors:&#xA; Neil Mackenzie - initial API and implementation&#xD;This file contains a representation of the data definition package  of the SMCubes Information Model. The SMCubes Information Model is freely available at https://www.ecb.europa.eu/stats/ecb_statistics/co-operation_and_standards/smcube/html/index.en.html"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="CUBE_MAPPING">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cube_mapping_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source_cube" eType="ecore:EClass data_definition.ecore#//CUBE"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target_cube" eType="ecore:EClass data_definition.ecore#//CUBE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maintenance_agency_id"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappingsToCube" upperBound="-1"
        eType="#//MAPPING_TO_CUBE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MEMBER_MAPPING">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maintenance_agency_id"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="member_mapping_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberMappingItems" upperBound="-1"
        eType="#//MEMBER_MAPPING_ITEM" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MEMBER_MAPPING_ITEM">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" eType="ecore:EClass core.ecore#//MEMBER"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="ecore:EClass core.ecore#//VARIABLE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VARIABLE_MAPPING_ITEM">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="ecore:EClass core.ecore#//VARIABLE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VARIABLE_MAPPING">
    <eStructuralFeatures xsi:type="ecore:EReference" name="varaibleMappingItems" upperBound="-1"
        eType="#//VARIABLE_MAPPING_ITEM" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maintenance_agency_id"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable_mapping_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAPPING_TO_CUBE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping" eType="#//MAPPING_DEFINITION"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VARIABLE_SET_MAPPING">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceMapping" eType="#//MAPPING_DEFINITION"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetMapping" eType="#//MAPPING_DEFINITION"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MAPPING_DEFINITION">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maintenance_agency_id"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapping_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapping_type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="memberMapping" eType="#//MEMBER_MAPPING"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableMapping" eType="#//VARIABLE_MAPPING"/>
  </eClassifiers>
</ecore:EPackage>
