<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cube_transformation_logic" nsURI="http://www.eclipse.org/efbt/cube_transformation_logic"
    nsPrefix="cube_transformation_logic">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value=" This package describes the logic for cube transformations  &#xA;&#xD;&#xA;"/>
  </eAnnotations>
  <eAnnotations source="license">
    <details key="license" value="Copyright (c) 2020 Bird Software Solutions Ltd&#xA; All rights reserved. This file and the accompanying materials are made available under the terms of the Eclipse Public License v2.0 which accompanies this distribution, and is available at http://www.eclipse.org/legal/epl-v20.html&#xA;&#xA;SPDX-License-Identifier: EPL-2.0 &#xA;&#xA; Contributors:&#xA; Neil Mackenzie - initial API and implementation&#xD;"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="CubeTransformationLogic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnFunctionGroup" eType="ecore:EClass ../../org.eclipse.efbt.cocamo.lineage.model.lineagefunctions/model/column_transformation_logic.ecore#//ColumnFunctionGroup"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rowCreationApproachForCube"
        eType="ecore:EClass row_transformation_logic.ecore#//RowCreationApproachForCube"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usedInSubsets" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
