<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testmodel" nsURI="testmodel" nsPrefix="testmodel">
  <eClassifiers xsi:type="ecore:EClass" name="TestModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Child" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="singleOptional" eType="#//SingleOptional"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="singleRequired" lowerBound="1"
        eType="#//SingleRequired" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeSample" eType="#//AttributeSample"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkToSingleRequired" eType="#//SingleRequired"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceTestContainer"
        upperBound="-1" eType="#//ReferenceTestContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeTest" upperBound="-1"
        eType="#//AttributeTestContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nameAttributeTest" upperBound="-1"
        eType="#//NameAttributeContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sub" eType="#//testsubmodel/TestInnerModel"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Child">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceList" upperBound="-1"
        eType="#//SingleRequired"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleOptional" eSuperTypes="#//Interface"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingleRequired" eSuperTypes="#//Abstract #//SingleOptional">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedElements" upperBound="-1"
        eType="#//NestedElements" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nestedElement" eType="#//NestedElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Abstract" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentReference" eType="#//TestModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentContainment" eType="#//Interface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NestedElements"/>
  <eClassifiers xsi:type="ecore:EClass" name="NestedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeSample">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="singleIntOptional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listIntRequired" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigDecimal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bigInteger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="double" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceTestContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containments" upperBound="-1"
        eType="#//ReferenceTarget" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceToOne" eType="#//ReferenceTarget"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceToMany" upperBound="-1"
        eType="#//ReferenceTarget"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containment" eType="#//ReferenceTarget"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oneAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manyAttributes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceTarget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceTargetSubclass" eSuperTypes="#//ReferenceTarget"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeTestContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oneInt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oneInteger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manyInt" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oneBool" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manyBool" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oneDouble" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manyDouble" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oneBigDecimal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manyBigDecimal" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oneBigInteger" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manyBigInteger" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oneEnum" eType="#//SampleEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manyEnums" upperBound="-1"
        eType="#//SampleEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oneShort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manyShorts" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oneDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manyDates" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oneString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manyString" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameAttributeContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultNameTest" eType="#//DefaultName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customNameTest" eType="#//CustomName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="noNameTest" eType="#//NoName"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefaultName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NoName"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SampleEnum">
    <eLiterals name="Sample"/>
    <eLiterals name="Sample2" value="1" literal="Sample2"/>
  </eClassifiers>
  <eSubpackages name="testsubmodel" nsURI="testmodel.testsubmodel" nsPrefix="testsubmodel">
    <eClassifiers xsi:type="ecore:EClass" name="TestInnerModel"/>
  </eSubpackages>
  <eSubpackages name="testsubmodelWithTraditionalURI" nsURI="http://testmodel/subWithTraditionalURI/1.0"
      nsPrefix="testsubmodelWithTraditionalURI">
    <eClassifiers xsi:type="ecore:EClass" name="TestInnerModelInPackageWithTraditionalURI">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
